### ISSUE TITLE
Server Crash by Forestry 

### ISSUE THREAD

**Issue by ClexOfficial** [ForestryMC/ForestryMC#2052] opened 2018-03-24 00:22 UTC
So I set up a modpack and the mod works fine but in the server this happens
Crash Log
https://pastebin.com/n25VZrv0
If anyone   know how to fix please let me know
Thanks in advance!

**Comment by ClexOfficial** [comment] 2018-03-24 00:26
Version is 1.7.10

**Comment by Nedelosk** [comment] 2018-03-24 00:44
Duplicate of #1936

**Closed as completed** 2018-04-06 14:20 UTC
Labels: duplicate
