### ISSUE TITLE
Crash on start-up 1.10-2

### ISSUE THREAD

**Issue by Jesperson** [ForestryMC/ForestryMC#1383] opened 2016-08-12 09:41 UTC
Crash report: http://pastebin.com/XA8WjVwL
Forge v.: 1.10-2-12.18.1.2011

**Comment by squirrelkiller** [comment] 2016-08-12 10:34
[crash-2016-08-12_06.24.01-client.txt](https://github.com/ForestryMC/ForestryMC/files/415114/crash-2016-08-12_06.24.01-client.txt)
have another, same issue from that report.

**Comment by Nedelosk** [comment] 2016-08-12 10:48
Thanks for the report!
But this is a duplicate of #1382.

**Closed as completed** 2016-08-12 10:49 UTC
Labels: duplicate
