### ISSUE TITLE
Cannot open multifarm GUI with an OpenGL Error (forestry_1.9-5.0.0.42)

### ISSUE THREAD

**Issue by gonglinyuan** [ForestryMC/ForestryMC#1226] opened 2016-05-23 05:44 UTC
![image](https://cloud.githubusercontent.com/assets/9744170/15461163/f8957c2a-20ea-11e6-822d-f8414b27f516.png)
The GUI of the multifarm is blank(even without inventories) and cannot be used. And an OpenGL error is detected.

Also, a NullPointerException is reported in the fml-client-latest.log:
`[13:33:53] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.NullPointerException
[13:33:53] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:    at forestry.farming.gui.FarmLedger.draw(FarmLedger.java:58)
[13:33:53] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:    at forestry.core.gui.ledgers.Ledger.draw(Ledger.java:147)
[13:33:53] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:    at forestry.core.gui.ledgers.LedgerManager.drawLedgers(LedgerManager.java:138)
[13:33:53] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:    at forestry.core.gui.GuiForestry.drawWidgets(GuiForestry.java:211)
[13:33:53] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:    at forestry.core.gui.GuiForestry.func_146976_a(GuiForestry.java:203)
[13:33:53] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:    at forestry.core.gui.GuiForestryTitled.func_146976_a(GuiForestryTitled.java:27)
[13:33:53] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:    at forestry.farming.gui.GuiFarm.func_146976_a(GuiFarm.java:55)
[13:33:53] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:76)
[13:33:53] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:355)
[13:33:53] [Client thread/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:    ... 14 more`

And this is the file

[fml-client-latest.zip](https://github.com/ForestryMC/ForestryMC/files/276865/fml-client-latest.zip)

**Comment by mezz** [comment] 2016-05-23 06:50
Thanks for the report!
I think this is a duplicate of: https://github.com/ForestryMC/ForestryMC/issues/1209
Please try with the latest build.

**Comment by mezz** [comment] 2016-05-23 20:38
@gonglinyuan can you confirm?

**Comment by gonglinyuan** [comment] 2016-05-24 04:56
@mezz Yes. This bug does not exist in forestry_1.9-5.0.0.58. Thank you!

**Comment by mezz** [comment] 2016-05-24 04:57
Thanks for reporting glad it works now.

**Closed as completed by mezz** 2016-05-24 04:57 UTC
Labels: duplicate
