### ISSUE TITLE
[1.12] Log errors when plugins are disabled due to the loot tables.

### ISSUE THREAD

**Issue by TeknoKit** [ForestryMC/ForestryMC#1781] opened 2017-07-31 08:32 UTC
When "B:forestry.storage=false", the startup log throws an error over the loot table "forestry:chests/abandoned_mineshaft" because the "forestry:miner_bag" was never registered. The game continues to load and does not crash.
Disabling other plugins would cause similar errors with their items in the loot tables.
I realize it simply fails to load the loot table the item is missing for which has no negative impact on running, but this spams the logs with stacktraces at every startup. This has been the case for quite a while actually, looking back.

https://gist.github.com/TeknoKit/7cbc5e962df28340b2c2e9b24b3cee0d

Forge: 1.12-14.21.1.2428
Forestry: 1.12-5.5.0.154

(Can they use something like the condition factory system?)

**Comment by Nedelosk** [comment] 2017-07-31 08:48
Duplicate of #1375

**Closed as completed by Nedelosk** 2017-07-31 08:48 UTC
Labels: duplicate
