### ISSUE TITLE
Forestry Wood Slabs NEI duplicates

### ISSUE THREAD

**Issue by iRhuel** [ForestryMC/ForestryMC#1054] opened 2016-02-01 21:20 UTC
Hello, 

I recently updated from Forestry 3.6.11 to 4.2.6 (was playing on an old modpack up til now.) After the update, all Forestry wood slabs (regular and fireproof) have two entries in NEI, using different block IDs. One entire set (reg and fireproof) renders as Larch Wood **Planks**, while the other shows normally as their respective **slabs**. Screenshots for reference:

_imgur went down as I wrote this, will post images later_

EDIT: http://imgur.com/a/4e4XL

I suspect this has to do with the switch in versions, but have no idea how to resolve this. Already removed the old .conf files in /config folder, but other than that I'm really not well versed enough to do more.

 Thanks in advance for any help.

**Comment by mezz** [comment] 2016-02-02 01:43
Thanks for the report!
Does it show that way in the creative menu? It may be an NEI bug.

**Comment by iRhuel** [comment] 2016-02-02 02:42
Just searched all the creative tabs. Looks like the bugged duplicates are nowhere to be found. S

Does that point to an NEI problem? Is there a way to 'reset' NEI or find out where it's pulling these block IDs from?

Here's something interesting. I tried placing one of the bugged slabs. It renders in the world as a double slab version of whatever wood it's supposed to be. Coloring is correct, unlike in NEI. Once broken, it returns 2x wooden slabs... of the correct block ID of whatever wood type it was. 

screen caps: http://imgur.com/a/2080U

You'll notice in the second cap, the broken slabs have stacked with the slab with the 'correct' item ID.

This is so strange...

**Comment by mezz** [comment] 2016-02-02 02:44
Ah ok. I recently added double slabs to Forestry, which is why the problem is only coming up now. They're not in the creative menu, since you shouldn't be able to get them in the game. I'm not sure why NEI is showing them.

**Comment by iRhuel** [comment] 2016-02-02 06:57
I see. Is it unique to me, then? Must be something about my setup. They're a minor annoyance, but it's not game breaking or anything.

**Comment by mezz** [comment] 2016-02-02 07:01
No, I checked and I see them in NEI too. 
Can you report to NEI to see if they know what the issue might be? 
https://github.com/Chicken-Bones/NotEnoughItems/issues

**Comment by iRhuel** [comment] 2016-02-02 07:42
Of course. Anything in particular I should mention to them?

**Comment by labpaw** [comment] 2016-02-02 17:08
Not really a bug. NEI displays double slabs from vanilla and other mods.

**Comment by mezz** [comment] 2016-05-01 16:20
Since NEI is not being maintained and this is not a problem in 1.8+ with JEI, I am going to close this issue.

**Closed as completed by mezz** 2016-05-01 16:20 UTC
Labels: Not Forestry
