### ISSUE TITLE
Forestry: Texture load failure

### ISSUE THREAD

**Issue by Yamza** [ForestryMC/ForestryMC#2263] opened 2018-10-02 21:01 UTC
This error seems to be causing Minecraft to load with white textures. Sometimes it will work normally, and sometimes it will crash. Has been an ongoing issue over several versions.

https://hastebin.com/itologebaj.coffeescript

Minecraft 1.12.2
Forge 14.23.4.2759
forestry 1.12.2 5.8.1.339
Modpack: ATM3 - Remix 0.0.2

Has been tested without optifine.

**Comment by temp1011** [comment] 2018-10-12 13:36
```Caused by: net.minecraft.client.renderer.StitcherException: Unable to fit: forestry:gui/mail/carrier.player, size: 32x32, atlas: 0x0, atlasMax: -1x-1 - Maybe try a lower resolution resourcepack?```
That is a weird atlas size. Maybe an OOM problem?

**Comment by Yamza** [comment] 2018-10-12 16:28
There was no resource pack used. Ram was set to this (11980 MB), which is a bit high for ATM3. Or are you referring to disk space?

**Comment by temp1011** [comment] 2018-10-13 14:39
Similar crashes seemed to be caused by low RAM but you have a lot allocated so I'm not sure if that is the problem here. If you can get the game to load you could try using https://github.com/mezz/TextureDump to see if anything if taking up a lot of space. Alternatively, maybe this is some kind of forestry bug.

It may be also worth checking if removing a couple of texture heavy mods (most likely ones with many items/blocks) so see if the crashes stop.

**Comment by Nedelosk** [comment] 2019-09-26 19:10
@Yamza Any update on this?

**Comment by Nedelosk** [comment] 2020-03-03 19:40
I will close this because we didn't get a response.

**Closed as completed by Nedelosk** 2020-03-03 19:40 UTC
Labels: Bug-major
