### ISSUE TITLE
[1.11.2] Crash when break Farm Block

### ISSUE THREAD

**Issue by KorDum** [ForestryMC/ForestryMC#1864] opened 2017-10-03 17:06 UTC
https://gist.github.com/KorDum/764efea8e3df3ae3d8632d385e676c14

One of the players broke Farm Block from a de-energized multifarm. Then there was a crash.
Why did this happen?

**Comment by Nedelosk** [comment] 2017-10-12 09:56
We have no idea what causes this crash. Duplicate of #1132.

**Closed as completed by Nedelosk** 2017-10-12 09:56 UTC
Labels: duplicate
