### ISSUE TITLE
Crash putting Ender Queen into Apiary/Beehouse

### ISSUE THREAD

**Issue by Orcinuss** [ForestryMC/ForestryMC#1523] opened 2016-12-03 00:05 UTC
Putting an Ender Queen into an Apiary or a Beehouse crashes the server. 
Directly putting in the Ender queen will crash the server.
Putting a princess and a drone in will also crash the server once they turn into a queen.

Crash Report: http://pastebin.com/krCtaKgf

Minecraft 1.10.2
Forestry v5.2.16.330
Direwolf20 Pack v1.1.0
Forge 12.18.2.2171

**Comment by Nedelosk** [comment] 2016-12-22 03:33
Have you edited the nbt tags ? If not you have done anything wrong, because you are the only one with this problems.

**Comment by Nedelosk** [comment] 2017-01-01 03:20
Has anyone else this bug, if not I will close this.

**Comment by mezz** [comment] 2017-01-01 07:33
I think this has the same root cause as #1524

**Closed as completed** 2017-04-05 12:43 UTC
