### ISSUE TITLE
NOSUCHMETHODERROR crash

### ISSUE THREAD

**Issue by MidCoard** [ForestryMC/ForestryMC#2518] opened 2020-02-05 14:51 UTC
[FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$WorldTickEvent@24f25614:
java.lang.NoSuchMethodError: forestry.core.utils.InventoryUtil.internal_moveOneItemToPipe(Lnet/minecraftforge/items/IItemHandler;Lforestry/core/tiles/AdjacentTileCache;[Lnet/minecraft/util/EnumFacing;)Z
	at forestry.core.utils.InventoryUtil.moveOneItemToPipe(InventoryUtil.java:82) ~[InventoryUtil.class:?]
	at forestry.farming.tiles.TileFarmHatch.updateServer(TileFarmHatch.java:67) ~[TileFarmHatch.class:?]
	at forestry.farming.multiblock.FarmController.updateServer(FarmController.java:246) ~[FarmController.class:?]
	at forestry.core.multiblock.MultiblockControllerBase.updateMultiblockEntity(MultiblockControllerBase.java:445) ~[MultiblockControllerBase.class:?]
	at forestry.core.multiblock.MultiblockWorldRegistry.tickStart(MultiblockWorldRegistry.java:82) ~[MultiblockWorldRegistry.class:?]
	at forestry.core.multiblock.MultiblockRegistry.tickStart(MultiblockRegistry.java:33) ~[MultiblockRegistry.class:?]
	at forestry.core.multiblock.MultiblockServerTickHandler.onWorldTick(MultiblockServerTickHandler.java:20) ~[MultiblockServerTickHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_595_MultiblockServerTickHandler_onWorldTick_WorldTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:287) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:752) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]

My forge server (forge12.2 14.23.5.2847 should be the newest.)crashed in version of forestry_1.12.2-5.8.2.387.

i think i should use one BETA version.Hope to fix the bug. tks.

**Comment by MidCoard** [comment] 2020-02-05 14:53
It should be that when i destoryed one block of the farming system,it crashed.

**Comment by MidCoard** [comment] 2020-02-05 15:08
Sorry for that the things did not turn good.I have used the BETA version,but there was nothing what i expected to happen.Still crashed.Help me!!!!

**Comment by MidCoard** [comment] 2020-02-05 15:17
Oh, aha. I used the historic version.That is!!!!!!
I can run my server with the version of forestry_1.12.2-5.8.2.374.It is an old version while it is really good,
Hope you guys could fix the bug of the new versions.:):):):)

**Comment by Nedelosk** [comment] 2020-02-07 14:37
Duplicate of #2455

**Closed as completed by Nedelosk** 2020-02-07 14:37 UTC
Labels: duplicate

**Comment by MIdCoard** [comment] 2020-02-08 00:44
So has this bug been fixed up?I have tried the newest version, but it seemed that it did not be fixed up.

**Comment by MidCoard** [comment] 2020-02-08 05:50
I think i have said that **it has occured again in the newest version.**
I LOOK FOR THE SOLUTION IN #2477 ,finding that 

'The new curseforge website layout shows the very old last release build above the latest beta ones. Your crash should be fixed by the version of forestry from here: https://www.curseforge.com/minecraft/mc-mods/forestry/files/2755279.'

SO I TRIED THIS VERSION JUST NOW.THERE IS NO WAY OUT.

So has this bug been fixed up?

Or it has not been fixed up yet?
