### ISSUE TITLE
Crash in BeeHousingModifier.getTerritoryModifier()

### ISSUE THREAD

**Issue by KorDum** [ForestryMC/ForestryMC#1042] opened 2016-01-15 18:07 UTC
https://gist.github.com/mezz/48152b849dcbf5042589

**Comment by mezz** [comment] 2016-01-15 19:54
Thanks for the report!
This is a duplicate of https://github.com/ForestryMC/ForestryMC/issues/857
Binnie's does not work with Forestry 4 yet.

**Closed as completed by mezz** 2016-01-15 19:54 UTC
Labels: duplicate
