### ISSUE TITLE
Crash forestry 382

### ISSUE THREAD

**Issue by Neuromantix** [ForestryMC/ForestryMC#2351] opened 2019-01-25 15:41 UTC
---- Minecraft Crash Report ----

// Oops.

Time: 1/25/19 6:38 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: forestry.core.utils.InventoryUtil.internal_moveOneItemToPipe(Lnet/minecraftforge/items/IItemHandler;Lforestry/core/tiles/AdjacentTileCache;[Lnet/minecraft/util/EnumFacing;)Z
	at forestry.core.utils.InventoryUtil.moveOneItemToPipe(InventoryUtil.java:82)
	at forestry.farming.tiles.TileFarmHatch.updateServer(TileFarmHatch.java:67)
	at forestry.farming.multiblock.FarmController.updateServer(FarmController.java:246)
	at forestry.core.multiblock.MultiblockControllerBase.updateMultiblockEntity(MultiblockControllerBase.java:445)
	at forestry.core.multiblock.MultiblockWorldRegistry.tickStart(MultiblockWorldRegistry.java:82)
	at forestry.core.multiblock.MultiblockRegistry.tickStart(MultiblockRegistry.java:33)
	at forestry.core.multiblock.MultiblockServerTickHandler.onWorldTick(MultiblockServerTickHandler.java:20)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1960_MultiblockServerTickHandler_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:287)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:752)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Nedelosk** [comment] 2019-01-25 16:16
Duplicate of #2340

**Closed as completed by Nedelosk** 2019-01-25 16:16 UTC
Labels: duplicate
