### ISSUE TITLE
[Forestry]: Missing primary allele: {null, null}

### ISSUE THREAD

**Issue by Tsyklop** [ForestryMC/ForestryMC#998] opened 2015-12-04 08:16 UTC
I create or go to the already created world and I see in the log is.
http://pastebin.com/r4Rt1pZs

forestry_1.7.10-4.2.1.48
Other mods: http://pastebin.com/1PRRDsFZ

**Comment by mezz** [comment] 2015-12-04 08:23
Thanks for the report!
Your log has errors all over the place from many mods, not just Forestry. 
I can't really make sense of it, I think something is very wrong.

**Comment by Tsyklop** [comment] 2015-12-04 08:34
@mezz This may be due to the fact that I updated Gendustry in Forestry together.
With Forestry 4.2.0 this error is not present.

**Comment by Tsyklop** [comment] 2015-12-04 08:45
https://github.com/bdew/gendustry/issues/148

**Comment by bdew** [comment] 2015-12-04 09:35
I've seen the log spam with 4.2.0, not sure if it has anything to do with gendustry, will look into this.

**Comment by bdew** [comment] 2015-12-04 10:23
I don't think it's related to the issue @Tsyklop linked, i was just doing something stupid when registering alleles.

I can't reproduce the log spam now (with or without the fix to that bug).

**Comment by mezz** [comment] 2015-12-06 02:35
I'm going to close this for now. Feel free to open a new issue if something else is still erroring.

**Closed as completed by mezz** 2015-12-06 02:35 UTC
