### ISSUE TITLE
Crash with Forestry 4.0.0.644-unstable and HEE

### ISSUE THREAD

**Issue by Xen1290** [ForestryMC/ForestryMC#773] opened 2015-07-25 21:30 UTC
Hi @mezz ,@Nirek-K I get that crash, fresh install:
https://gist.github.com/Xen1290/65a1adac4c5bb178aeaf
In this crash you can find the modlist.
Relevant mods:
Forge 10.13.4.1492
Forestry 4.0.0.644-unstable

**Comment by Zedrimar** [comment] 2015-07-28 04:02
confirmed

**Comment by mezz** [comment] 2015-08-02 01:35
Thanks for the report!  
Unfortunately I'm not able to reproduce this issue. I pushed some changes that might help figure it out though.
Can you delete your config folder again, grab the [latest unstable build (651+)](http://jenkins.ic2.player.to/job/Forestry_Dev/), run and paste the entire forge log to gist?

Thank you!

**Comment by Xen1290** [comment] 2015-08-02 16:42
Hi @mezz , Tested with 652, fresh install, I get another error.
P.S. a config file that forestry generates for the first time is empty(apicolture.cfg is completly empty.)
Entire fml-client-latest with the error, I have no crash reports:
https://gist.github.com/Xen1290/3bb0c9159595bad004b1
EDIT: When I tried to launch the game for the second time I get no crash, and the apicolture.cfg appear like this: https://gist.github.com/Xen1290/00625e35d43416b52196

**Comment by mezz** [comment] 2015-08-07 06:26
Thanks for the logs!
This appears to be the core issue: https://gist.github.com/mezz/5ef6241ccd2800d631b1
Investigating...

**Comment by Xen1290** [comment] 2015-08-07 06:46
Thanks!

**Comment by mezz** [comment] 2015-08-08 22:53
Ok I pushed some more changes that will narrow down the issue further.

Can you delete your config folder again, grab the [latest unstable build (657+)](http://jenkins.ic2.player.to/job/Forestry_Dev/), run and paste the entire forge log to gist?

Thank you!

**Comment by Xen1290** [comment] 2015-08-09 22:03
Here you are @mezz !
With build 657
https://gist.github.com/Xen1290/c735e1878c619563442c
From the log, I think is HEE, by @chylex

" Caused by: java.lang.IllegalArgumentException: can't parse argument number: block=chylex.hee.block.BlockDragonEggCustom@5c57f445 "

**Comment by mezz** [comment] 2015-08-09 22:14
Yep, it's crashing on my error log ha. I'll fix the log but it still gave us the information we need.
Thanks for your help @Xen1290!

Looks like `BlockDragonEggCustom.delegate.name()` is returning null.
@chylex any idea why it might be doing that? This is during Init and Forestry is set to run after HEE.

**Comment by mezz** [comment] 2015-08-09 22:54
Talked to chylex in IRC and created a new issue: https://github.com/chylex/Hardcore-Ender-Expansion/issues/133

Pushed a fix that should allow you to start your game now! The dragon egg will not be available as a flower until HEE is fixed, but at least Forestry should run now. Let me know if you have any issues.

**Closed as completed** 2015-08-09 22:53 UTC
Labels: Bug-major

**Comment by Xen1290** [comment] 2015-08-09 22:56
Thanks for all!
