### ISSUE TITLE
[forestry-1.16.5-6.0.7] Game crash with MineColonies

### ISSUE THREAD

**Issue by RisingInIris2017** [ForestryMC/ForestryMC#2632] opened 2022-01-27 14:36 UTC
Game crashes when loading a world.
[Crash Report](https://gist.github.com/RisingInIris2017/a8fa5749bd31259ba924755dfacb3603)

**Comment by ramidzkh** [comment] 2022-01-27 23:21
Duplicate of #2629

**Closed as completed by ramidzkh** 2022-01-27 23:21 UTC
