### ISSUE TITLE
[1.12] [5.5.0.163] Rendering Item Crash

### ISSUE THREAD

**Issue by Alaberti** [ForestryMC/ForestryMC#1818] opened 2017-08-20 23:50 UTC
https://pastebin.com/JVk7xKDY

According to player: "Was looking at furnace recipes in JEI, arrowed over to the last tab which I think was Forestry, and crash."

**Comment by Nedelosk** [comment] 2017-08-21 11:50
Duplicate of #1598

**Closed as completed by Nedelosk** 2017-08-21 11:50 UTC
Labels: duplicate
