### ISSUE TITLE
1.9.4 [143] Crash when opening chest with old bees

### ISSUE THREAD

**Issue by Crazy-KSK** [ForestryMC/ForestryMC#1301] opened 2016-06-07 03:32 UTC
I got this crash upon opening a chest inside a village bee house that has been generated with a previous 1.9.4 forestry version, I remember that the chest did have some bees in it even though it cashes before showing the contents it only plays the opening sound 
http://pastebin.com/FRREvEXq

**Comment by mezz** [comment] 2016-06-07 04:44
Thanks for the report!
Dupe of https://github.com/ForestryMC/ForestryMC/issues/1276

> One of the first Forestry 5 release broke all the genes.
> In your config/forestry/common.cfg set genetics.clear.invalid.chromosomes to true.

**Closed as completed by mezz** 2016-06-07 04:44 UTC
Labels: duplicate
