### ISSUE TITLE
Game crash: CodeChickenLib caught exception whilst rendering an item.

### ISSUE THREAD

**Issue by RisingInIris2017** [ForestryMC/ForestryMC#2522] opened 2020-02-10 11:15 UTC
#### Mod version:
CCL Mod Version: CodeChickenLib-1.12.2-3.2.3.358
Suspected mod Forestry Version: forestry_1.12.2-5.8.2.387
Both the latest versions on CurseForge.

#### Forge version:

forge-1.12.2-14.23.5.2847

#### Singleplayer or Multiplayer:

Both singleplayer and multiplayer.

#### Installed mods:
In crash-report will you see a list for all installed mod.

## Link to full crash log
https://gist.github.com/RisingInIris2017/2ac429f0898d31339b4bb5218c48bff0

#### How to reproduce:

1. Use a tool with Silk Touch to harvest a Forestry Mod's leaf block.
2. Pick it up, and then open the Inventory.
3. Game crashes.
4. Every time the Inventory is opened, game crashes.

I do not know what happened, so I decided to turn to you dear devs.
I will post the same issue to [CodeChickenLib's GitHub](https://github.com/TheCBProject/CodeChickenLib/issues/288).

Looks forward to your reply!
Thanks in advance!

**Comment by Nedelosk** [comment] 2020-02-15 09:17
This bug is already fixed in the newer versions. Please update to a newer version like 5.8.2.409.

**Comment by Nedelosk** [comment] 2020-02-15 09:17
Duplicate of #2336

**Closed as completed by Nedelosk** 2020-02-15 09:17 UTC
Labels: duplicate
