### ISSUE TITLE
1.10.2 Carpenter recipes dont consume enough items

### ISSUE THREAD

**Issue by mcenderdragon** [ForestryMC/ForestryMC#1448] opened 2016-10-07 21:37 UTC
In Forestry 5..2.12.258 the Carpenter dont use enough items if you craft the Camouflaged paneling. All required items must be there, but the stacksize is not checked.

Images:
http://imgur.com/npEXQwV
http://imgur.com/HtLCw5g

**Comment by Nedelosk** [comment] 2016-10-08 09:49
Thanks for the report!
I think the carpenter ore dictionary support is broken.

**Comment by mezz** [comment] 2016-10-09 02:06
Duplicate of #1364
Marking it as a major bug there

**Closed as completed by mezz** 2016-10-09 02:06 UTC
Labels: duplicate
