### ISSUE TITLE
[1.12.2-5.8.2.409] Tickin exception

### ISSUE THREAD

**Issue by warmist** [ForestryMC/ForestryMC#2506] opened 2019-12-27 11:52 UTC
Looks like it's crashing when testing for similar saplings. Not many mods (~10). With binnie mods.
Crash at:

forestry.arboriculture.genetics.TreeGrowthHelper.hasSufficientSaplingsAroundSapling(TreeGrowthHelper.java:65)

Full log: [here](https://gist.github.com/warmist/6a5bbbea36760bc7604abe0496d78f69)

**Comment by warmist** [comment] 2019-12-29 12:36
Looking over more logs, it seems that all of them contain stack traces for binnie tree growth. Should i move this issue there?

**Comment by MrZSFG** [comment] 2020-02-08 20:37
Getting the same issue still can't find a fix for it 
Raw log: https://pastebin.com/8ytVq8Uw

**Comment by Nedelosk** [comment] 2020-02-26 19:04
Duplicate of https://github.com/ForestryMC/Binnie/issues/626

**Closed as completed by Nedelosk** 2020-02-26 19:04 UTC
Labels: duplicate, Not Forestry
