### ISSUE TITLE
Ticking World Exception

### ISSUE THREAD

**Issue by joker-119** [ForestryMC/ForestryMC#2323] opened 2018-12-22 11:22 UTC
// On the bright side, I bought you a teddy bear!

Time: 12/22/18 3:17 AM
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:542)
	at net.minecraft.world.World.func_180501_a(World.java:343)
	at net.minecraft.world.World.func_175656_a(World.java:425)
	at forestry.arboriculture.tiles.TileLeaves.onBlockTick(TileLeaves.java:154)
	at forestry.arboriculture.blocks.BlockForestryLeaves.func_180650_b(BlockForestryLeaves.java:100)
	at net.minecraft.block.Block.func_180645_a(Block.java:508)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:476)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

It seems to happen pretty randomly. Sometimes just while running around, sometimes while loading new chunks, sometimes when teleporting. Doing the same things doesn't always cause the crash again (IE: Teleporting from one player to another can cause the crash, but once we login, if I go back then teleport to them again, nothing.

**Comment by Nedelosk** [comment] 2018-12-23 11:58
Please update Binnies mods.

**Comment by Nedelosk** [comment] 2018-12-23 11:59
Duplicate of #2317

**Closed as completed by Nedelosk** 2018-12-23 11:59 UTC
Labels: duplicate
