### ISSUE TITLE
Crash on startup with forestry_1.10.2-5.2.7.228

### ISSUE THREAD

**Issue by MokahTGS** [ForestryMC/ForestryMC#1384] opened 2016-08-12 16:33 UTC
Getting a crash on startup:  http://pastebin.com/vHKdnLyn

**Comment by MakerTim** [comment] 2016-08-12 16:59
Got the same crash in my environment 
http://pastebin.com/LH9wZc0s

**Comment by kreezxil** [comment] 2016-08-12 17:20
confirmed for the client but ok on dedicated server!

http://pastebin.com/qi7SmrZZ

**Comment by Redlotus99** [comment] 2016-08-12 18:00
I can confirm this also. Getting the same error.

http://pastebin.com/75KXPpAW

**Comment by kreezxil** [comment] 2016-08-12 18:17
@Redlotus99 confirm it with an error report, otherwise it's just words.

**Comment by Redlotus99** [comment] 2016-08-12 18:21
@kreezxil I suppose I can post the same error as everyone else a 4th time.

**Comment by Utildayael** [comment] 2016-08-12 18:22
Ditto. Same error. Full log in pastebin.

http://pastebin.com/xf3t9YGq

```
Description: Initializing game

java.lang.AbstractMethodError: forestry.arboriculture.blocks.WoodTypeStateMapper.getModelResourceLocation(Lnet/minecraft/block/state/IBlockState;)Lnet/minecraft/client/renderer/block/model/ModelResourceLocation;
    at forestry.arboriculture.proxy.ProxyArboricultureClient.onModelBake(ProxyArboricultureClient.java:140)
    at forestry.arboriculture.PluginArboriculture.onModelBake(PluginArboriculture.java:578)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_391_PluginArboriculture_onModelBake_ModelBakeEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)
    at net.minecraftforge.client.ForgeHooksClient.onModelBake(ForgeHooksClient.java:400)
    at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:30)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
    at elec332.core.client.model.ElecResourceManager.func_110541_a(ElecResourceManager.java:55)
    at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:755)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:338)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by October45** [comment] 2016-08-12 18:26
http://pastebin.com/Lg1aemqs

**Comment by Redlotus99** [comment] 2016-08-12 19:09
https://github.com/ForestryMC/ForestryMC/issues/1382 may be related

**Comment by Nedelosk** [comment] 2016-08-12 19:40
Thanks for the report!
But this is a duplicate of #1382.

**Closed as completed by Nedelosk** 2016-08-12 19:40 UTC
Labels: duplicate
