### ISSUE TITLE
Lepidoptery crash

### ISSUE THREAD

**Issue by VictorScrooge** [ForestryMC/ForestryMC#1934] opened 2018-01-03 17:12 UTC
Hello, i am using the 5.7.0.219 Version and got a crash because of this

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoreMod (Aroma1997Core-1.12.2-1.3.0.2.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-75-core.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  AstralCore (astralsorcery-1.12.2-1.8.4.jar)
  LoadingPlugin (AdFinders-1.12.1-2.1.1.0-build.0056.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.3.9.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.3.0.jar)
  FarseekCoreMod (Farseek-1.12-2.2.2.jar)
  LoadingPlugin (AdChimneys-1.12.1-3.2.1.0-build.0056.jar)
  DummyPlugin (ForgeEndertech-1.12.1-4.3.0.0-build.0056.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 1/2/18 5:36 AM
Description: Rendering item

java.lang.NullPointerException: Rendering item
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
	at forestry.lepidopterology.render.ModelButterflyItem$ButterflyItemOverrideList.handleItemState(ModelButterflyItem.java:89)
	at net.minecraft.client.renderer.RenderItem.func_184393_a(RenderItem.java:243)
	at codechicken.lib.render.item.CCRenderItem.func_184393_a(CCRenderItem.java:258)
	at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:210)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:265)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:98)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:643)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:353)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

If you need, i give you the complete log.

**Comment by temp1011** [comment] 2018-01-04 01:23
Same as https://github.com/ForestryMC/ForestryMC/issues/1919?
EDIT: I maybe have an idea where this is coming from.

**Comment by temp1011** [comment] 2018-01-04 20:31
Ok here's what I think is possibly causing this:

https://github.com/ForestryMC/ForestryMC/blob/5a10d8a0b2e2f6cef62cdd81cf06219604407eca/src/main/java/forestry/lepidopterology/render/ModelButterflyItem.java#L87-L89
'IButterfly butterfly = ButterflyManager.butterflyRoot.getMember(stack);' this butterfly was sometimes created as null which caused the Null exception.

https://github.com/ForestryMC/ForestryMC/blob/5a10d8a0b2e2f6cef62cdd81cf06219604407eca/src/main/java/forestry/lepidopterology/genetics/ButterflyRoot.java#L143-L148
This was returning null when the butterfly was created in the constructor only using a genome (it's in the butterfly class).

Proposed solution: https://github.com/ForestryMC/ForestryMC/compare/mc-1.12...temp1011:fix-butterfly-crash (ignore first 4 commits, was new to Github and didn't branch, now until something happens to my current PR the other branches are out of sync).

It's not a very pretty solution and I'm not 100% the problem is what I think it is. That's why this isn't in a PR.

@mezz @Nedelosk If you could help a bad coder when you have the time (I understand it's Christmas) I would appreciate it. :)

**Comment by Nedelosk** [comment] 2018-01-05 14:40
Duplicate of #1919

**Closed as completed by Nedelosk** 2018-01-05 14:40 UTC
Labels: duplicate
