### ISSUE TITLE
Unable to Craft Biomass

### ISSUE THREAD

**Issue by Ruffage** [ForestryMC/ForestryMC#2117] opened 2018-04-30 22:14 UTC
I am unable to create Biomass in the Fermenter with Binnie's Bees installed. I have tried all of the Fertalizers and liquid combinations.

**Comment by temp1011** [comment] 2018-04-30 23:59
Do you just have those two mods installed?

**Comment by ProsperCraft** [comment] 2018-05-01 06:24
Yes, here is the modpack - https://minecraft.curseforge.com/projects/towncraft

The fuel will not go into the fuel slot - fert, mulch, compost.
Here is a video showing the issue- https://gyazo.com/217da94c08cd824e8b7831d9e354669f

**Comment by Nedelosk** [comment] 2018-05-01 07:57
Duplicate of #2082

**Closed as completed by Nedelosk** 2018-05-01 07:57 UTC
Labels: duplicate

**Comment by ProsperCraft** [comment] 2018-05-01 09:19
This is a duplicate of itself?

**Comment by temp1011** [comment] 2018-05-01 14:14
Hmm there are a lot of mods. I would tentatively suggest that this is a cross mod issue but I may well be wrong. I'm guessing this is on a server since that seems to be what the pack is designed for?

**Comment by ProsperCraft** [comment] 2018-05-01 14:15
Yes, we are on a server.  I can test in single player.
