### ISSUE TITLE
forestry:crated items causing crashes when looked up in JEI

### ISSUE THREAD

**Issue by jenrant** [ForestryMC/ForestryMC#2334] opened 2019-01-08 00:30 UTC
Crashed every time looking up something starting with "C" or "Co" in Just Enough Items. Disabling "forestry:crated.forestry.bee_combs.0" from showing up in JEI seemed to fix this issue, so I'm doing an issue report here.

Here's a crash report of it happening: [https://gist.github.com/JRantanenn/76417038efdd011851b3be8872a41c32](https://gist.github.com/JRantanenn/76417038efdd011851b3be8872a41c32)

There also appears to be another item that crashes JEI as well, which is "forestry:crated.natura.edibles.0"

Another crash report:
[https://gist.github.com/JRantanenn/caeabcac6304dcd4e5d7511c4d8e613f](https://gist.github.com/JRantanenn/caeabcac6304dcd4e5d7511c4d8e613f)

Edit: Found a couple other items that are causing the same crash in addition to the two above:
	forestry:crated.minecraft.cookie.0
	forestry:crated.minecraft.coal.1
	forestry:crated.minecraft.dye.4

**Comment by JRantanenn** [comment] 2019-01-09 23:00
There also appears to be another item that crashes JEI as well, which is "forestry:crated.natura.edibles.0"

Another crash report:
[https://gist.github.com/JRantanenn/caeabcac6304dcd4e5d7511c4d8e613f](https://gist.github.com/JRantanenn/caeabcac6304dcd4e5d7511c4d8e613f)

**Comment by Metasura** [comment] 2019-02-11 11:26
You can add this to the list
 forestry:crated.forestry.humus.0

Here crash report 
https://gist.github.com/Mimi4Craft/c385ac8a400b0f6a12026d7545ad823b

btw i'm using forestry_1.12.2-5.8.2.382
and forge 14.23.5.2811

**Comment by Nedelosk** [comment] 2019-09-26 20:04
Duplicate of #2395

**Closed as completed by Nedelosk** 2019-09-26 20:04 UTC
Labels: duplicate, JEI
