### ISSUE TITLE
Server Crash on Startup (Recipe Sorter)

### ISSUE THREAD

**Issue by Alrawn** [ForestryMC/ForestryMC#1295] opened 2016-06-05 22:35 UTC
Server worked with all other mods installed. adding forestry into the mix lead to this crash.

```
[00:11:34] [Server thread/INFO] [FML/]: Forge Mod Loader has successfully loaded 12 mods
[00:11:34] [Server thread/TRACE] [mcp/mcp]: Sending event FMLServerAboutToStartEvent to mod mcp
[00:11:34] [Server thread/TRACE] [mcp/mcp]: Sent event FMLServerAboutToStartEvent to mod mcp
[00:11:34] [Server thread/DEBUG] [FML/]: Bar Step: ServerAboutToStart - Minecraft Coder Pack took 0,000s
[00:11:34] [Server thread/TRACE] [FML/FML]: Sending event FMLServerAboutToStartEvent to mod FML
[00:11:34] [Server thread/TRACE] [FML/FML]: Sent event FMLServerAboutToStartEvent to mod FML
[00:11:34] [Server thread/DEBUG] [FML/]: Bar Step: ServerAboutToStart - Forge Mod Loader took 0,000s
[00:11:34] [Server thread/TRACE] [Forge/Forge]: Sending event FMLServerAboutToStartEvent to mod Forge
[00:11:34] [Server thread/TRACE] [Forge/Forge]: Sent event FMLServerAboutToStartEvent to mod Forge
[00:11:34] [Server thread/DEBUG] [FML/]: Bar Step: ServerAboutToStart - Minecraft Forge took 0,000s
[00:11:34] [Server thread/TRACE] [bagginses/bagginses]: Sending event FMLServerAboutToStartEvent to mod bagginses
[00:11:34] [Server thread/TRACE] [bagginses/bagginses]: Sent event FMLServerAboutToStartEvent to mod bagginses
[00:11:34] [Server thread/DEBUG] [FML/]: Bar Step: ServerAboutToStart - Bagginses took 0,000s
[00:11:34] [Server thread/ERROR] [BiomesOPlenty/]: Skipping event FMLServerAboutToStartEvent and marking errored mod BiomesOPlenty since required dependency Forge has errored
[00:11:34] [Server thread/DEBUG] [FML/]: Bar Step: ServerAboutToStart - Biomes O' Plenty took 0,001s
[00:11:34] [Server thread/ERROR] [chiselsandbits/]: Skipping event FMLServerAboutToStartEvent and marking errored mod chiselsandbits since required dependency Forge has errored
[00:11:34] [Server thread/DEBUG] [FML/]: Bar Step: ServerAboutToStart - Chisels & Bits took 0,001s
[00:11:34] [Server thread/TRACE] [fastleafdecay/fastleafdecay]: Sending event FMLServerAboutToStartEvent to mod fastleafdecay
[00:11:34] [Server thread/TRACE] [fastleafdecay/fastleafdecay]: Sent event FMLServerAboutToStartEvent to mod fastleafdecay
[00:11:34] [Server thread/DEBUG] [FML/]: Bar Step: ServerAboutToStart - Fast Leaf Decay took 0,000s
[00:11:34] [Server thread/ERROR] [forestry/]: Skipping event FMLServerAboutToStartEvent and marking errored mod forestry since required dependency Forge has errored
[00:11:34] [Server thread/DEBUG] [FML/]: Bar Step: ServerAboutToStart - Forestry took 0,002s
[00:11:34] [Server thread/ERROR] [JEI/]: Skipping event FMLServerAboutToStartEvent and marking errored mod JEI since required dependency Forge has errored
[00:11:34] [Server thread/DEBUG] [FML/]: Bar Step: ServerAboutToStart - Just Enough Items took 0,002s
[00:11:34] [Server thread/ERROR] [Quark/]: Skipping event FMLServerAboutToStartEvent and marking errored mod Quark since required dependency Forge has errored
[00:11:34] [Server thread/DEBUG] [FML/]: Bar Step: ServerAboutToStart - Quark took 0,001s
[00:11:34] [Server thread/TRACE] [randomthings/randomthings]: Sending event FMLServerAboutToStartEvent to mod randomthings
[00:11:34] [Server thread/TRACE] [randomthings/randomthings]: Sent event FMLServerAboutToStartEvent to mod randomthings
[00:11:34] [Server thread/DEBUG] [FML/]: Bar Step: ServerAboutToStart - Random Things took 0,000s
[00:11:34] [Server thread/TRACE] [xreliquary/xreliquary]: Sending event FMLServerAboutToStartEvent to mod xreliquary
[00:11:34] [Server thread/TRACE] [xreliquary/xreliquary]: Sent event FMLServerAboutToStartEvent to mod xreliquary
[00:11:34] [Server thread/DEBUG] [FML/]: Bar Step: ServerAboutToStart - Reliquary took 0,000s
[00:11:34] [Server thread/DEBUG] [FML/]: Bar Finished: ServerAboutToStart took 0,010s
[00:11:34] [Server thread/ERROR] [FML/]: Fatal errors were detected during the transition from AVAILABLE to SERVER_ABOUT_TO_START. Loading cannot continue
[00:11:34] [Server thread/ERROR] [FML/]: 
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAA mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJAA FML{8.0.99.99} [Forge Mod Loader] (forge-1.9.4-12.17.0.1954-universal.jar) 
    UCHIJEE Forge{12.17.0.1954} [Minecraft Forge] (forge-1.9.4-12.17.0.1954-universal.jar) 
    UCHIJAA bagginses{2.4.2b} [Bagginses] (Bagginses-1.9.4-2.4.2b.jar) 
    UCHIJEE BiomesOPlenty{4.1.0.2025} [Biomes O' Plenty] (BiomesOPlenty-1.9.4-4.1.0.2025-universal.jar) 
    UCHIJEE chiselsandbits{10.4} [Chisels & Bits] (chiselsandbits-10.4.jar) 
    UCHIJAA fastleafdecay{1.6} [Fast Leaf Decay] (FastLeafDecay-MC1.9.4-1.7.jar) 
    UCHIJEE forestry{5.0.8.141} [Forestry] (forestry_1.9.4-5.0.8.141.jar) 
    UCHIJEE JEI{3.4.3.207} [Just Enough Items] (jei_1.9.4-3.4.3.207.jar) 
    UCHIJEE Quark{beta-21} [Quark] (Quark-beta-21.jar) 
    UCHIJAA randomthings{3.7.3} [Random Things] (RandomThings-MC1.9.4-3.7.3.jar) 
    UCHIJAA xreliquary{1.9.4-1.3.2.372} [Reliquary] (Reliquary-1.9.4-1.3.2.372.jar) 
[00:11:34] [Server thread/ERROR] [FML/]: The following problems were captured during this phase
[00:11:34] [Server thread/ERROR] [FML/]: Caught exception from Forge
java.lang.IllegalArgumentException: Comparison method violates its general contract!
    at java.util.TimSort.mergeLo(Unknown Source) ~[?:1.8.0_31]
    at java.util.TimSort.mergeAt(Unknown Source) ~[?:1.8.0_31]
    at java.util.TimSort.mergeCollapse(Unknown Source) ~[?:1.8.0_31]
    at java.util.TimSort.sort(Unknown Source) ~[?:1.8.0_31]
    at java.util.Arrays.sort(Unknown Source) ~[?:1.8.0_31]
    at java.util.ArrayList.sort(Unknown Source) ~[?:1.8.0_31]
    at java.util.Collections.sort(Unknown Source) ~[?:1.8.0_31]
    at net.minecraftforge.oredict.RecipeSorter.sortCraftManager(RecipeSorter.java:154) ~[forge-1.9.4-12.17.0.1954-universal.jar:?]
    at net.minecraftforge.common.ForgeModContainer.onAvailable(ForgeModContainer.java:409) ~[forge-1.9.4-12.17.0.1954-universal.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.9.4.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.9.4.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.9.4.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.9.4.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.9.4.jar:?]
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:228) ~[forge-1.9.4-12.17.0.1954-universal.jar:?]
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:206) ~[forge-1.9.4-12.17.0.1954-universal.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.9.4.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.9.4.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.9.4.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.9.4.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.9.4.jar:?]
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135) [LoadController.class:?]
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:776) [Loader.class:?]
    at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:102) ~[FMLServerHandler.class:?]
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:325) [FMLCommonHandler.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:211) [lb.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:429) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_31]
[00:11:35] [Server thread/ERROR] [FML/]: A fatal exception occurred during the server about to start event
java.lang.IllegalArgumentException: Comparison method violates its general contract!
    at java.util.TimSort.mergeLo(Unknown Source) ~[?:1.8.0_31]
    at java.util.TimSort.mergeAt(Unknown Source) ~[?:1.8.0_31]
    at java.util.TimSort.mergeCollapse(Unknown Source) ~[?:1.8.0_31]
    at java.util.TimSort.sort(Unknown Source) ~[?:1.8.0_31]
    at java.util.Arrays.sort(Unknown Source) ~[?:1.8.0_31]
    at java.util.ArrayList.sort(Unknown Source) ~[?:1.8.0_31]
    at java.util.Collections.sort(Unknown Source) ~[?:1.8.0_31]
    at net.minecraftforge.oredict.RecipeSorter.sortCraftManager(RecipeSorter.java:154) ~[forge-1.9.4-12.17.0.1954-universal.jar:?]
    at net.minecraftforge.common.ForgeModContainer.onAvailable(ForgeModContainer.java:409) ~[forge-1.9.4-12.17.0.1954-universal.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.9.4.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.9.4.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.9.4.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.9.4.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.9.4.jar:?]
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:228) ~[LoadController.class:?]
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:206) ~[LoadController.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_31]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_31]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_31]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[minecraft_server.1.9.4.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[minecraft_server.1.9.4.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[minecraft_server.1.9.4.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[minecraft_server.1.9.4.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[minecraft_server.1.9.4.jar:?]
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135) ~[LoadController.class:?]
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:776) [Loader.class:?]
    at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:102) ~[FMLServerHandler.class:?]
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:325) [FMLCommonHandler.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:211) [lb.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:429) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_31]
[00:11:35] [Server thread/DEBUG] [FML/]: Reverting to frozen data state.
[00:11:35] [Server thread/TRACE] [mcp/mcp]: Sending event FMLModIdMappingEvent to mod mcp
[00:11:35] [Server thread/TRACE] [mcp/mcp]: Sent event FMLModIdMappingEvent to mod mcp
[00:11:35] [Server thread/DEBUG] [FML/]: Bar Step: ModIdMapping - Minecraft Coder Pack took 0,000s
[00:11:35] [Server thread/TRACE] [FML/FML]: Sending event FMLModIdMappingEvent to mod FML
[00:11:35] [Server thread/TRACE] [FML/FML]: Sent event FMLModIdMappingEvent to mod FML
[00:11:35] [Server thread/DEBUG] [FML/]: Bar Step: ModIdMapping - Forge Mod Loader took 0,000s
[00:11:35] [Server thread/TRACE] [Forge/Forge]: Sending event FMLModIdMappingEvent to mod Forge
[00:11:35] [Server thread/TRACE] [Forge/Forge]: Sent event FMLModIdMappingEvent to mod Forge
[00:11:35] [Server thread/DEBUG] [FML/]: Bar Step: ModIdMapping - Minecraft Forge took 0,076s
[00:11:35] [Server thread/TRACE] [bagginses/bagginses]: Sending event FMLModIdMappingEvent to mod bagginses
[00:11:35] [Server thread/TRACE] [bagginses/bagginses]: Sent event FMLModIdMappingEvent to mod bagginses
[00:11:35] [Server thread/DEBUG] [FML/]: Bar Step: ModIdMapping - Bagginses took 0,000s
[00:11:35] [Server thread/ERROR] [BiomesOPlenty/]: Skipping event FMLModIdMappingEvent and marking errored mod BiomesOPlenty since required dependency Forge has errored
[00:11:35] [Server thread/DEBUG] [FML/]: Bar Step: ModIdMapping - Biomes O' Plenty took 0,001s
[00:11:35] [Server thread/ERROR] [chiselsandbits/]: Skipping event FMLModIdMappingEvent and marking errored mod chiselsandbits since required dependency Forge has errored
[00:11:35] [Server thread/DEBUG] [FML/]: Bar Step: ModIdMapping - Chisels & Bits took 0,001s
[00:11:35] [Server thread/TRACE] [fastleafdecay/fastleafdecay]: Sending event FMLModIdMappingEvent to mod fastleafdecay
[00:11:35] [Server thread/TRACE] [fastleafdecay/fastleafdecay]: Sent event FMLModIdMappingEvent to mod fastleafdecay
[00:11:35] [Server thread/DEBUG] [FML/]: Bar Step: ModIdMapping - Fast Leaf Decay took 0,000s
[00:11:35] [Server thread/ERROR] [forestry/]: Skipping event FMLModIdMappingEvent and marking errored mod forestry since required dependency Forge has errored
[00:11:35] [Server thread/DEBUG] [FML/]: Bar Step: ModIdMapping - Forestry took 0,001s
[00:11:35] [Server thread/ERROR] [JEI/]: Skipping event FMLModIdMappingEvent and marking errored mod JEI since required dependency Forge has errored
[00:11:35] [Server thread/DEBUG] [FML/]: Bar Step: ModIdMapping - Just Enough Items took 0,000s
[00:11:35] [Server thread/ERROR] [Quark/]: Skipping event FMLModIdMappingEvent and marking errored mod Quark since required dependency Forge has errored
[00:11:35] [Server thread/DEBUG] [FML/]: Bar Step: ModIdMapping - Quark took 0,000s
[00:11:35] [Server thread/TRACE] [randomthings/randomthings]: Sending event FMLModIdMappingEvent to mod randomthings
[00:11:35] [Server thread/TRACE] [randomthings/randomthings]: Sent event FMLModIdMappingEvent to mod randomthings
[00:11:35] [Server thread/DEBUG] [FML/]: Bar Step: ModIdMapping - Random Things took 0,000s
[00:11:35] [Server thread/TRACE] [xreliquary/xreliquary]: Sending event FMLModIdMappingEvent to mod xreliquary
[00:11:35] [Server thread/TRACE] [xreliquary/xreliquary]: Sent event FMLModIdMappingEvent to mod xreliquary
[00:11:35] [Server thread/DEBUG] [FML/]: Bar Step: ModIdMapping - Reliquary took 0,000s
[00:11:35] [Server thread/DEBUG] [FML/]: Bar Finished: ModIdMapping took 0,080s
[00:11:35] [Server thread/INFO] [FML/]: Applying holder lookups
[00:11:35] [Server thread/INFO] [FML/]: Holder lookups applied
[00:11:35] [Server thread/DEBUG] [FML/]: Frozen state restored.
[00:11:35] [Server thread/TRACE] [mcp/mcp]: Sending event FMLServerStoppedEvent to mod mcp
[00:11:35] [Server thread/TRACE] [mcp/mcp]: Sent event FMLServerStoppedEvent to mod mcp
[00:11:35] [Server thread/DEBUG] [FML/]: Bar Step: ServerStopped - Minecraft Coder Pack took 0,000s
[00:11:35] [Server thread/TRACE] [FML/FML]: Sending event FMLServerStoppedEvent to mod FML
[00:11:35] [Server thread/TRACE] [FML/FML]: Sent event FMLServerStoppedEvent to mod FML
[00:11:35] [Server thread/DEBUG] [FML/]: Bar Step: ServerStopped - Forge Mod Loader took 0,000s
[00:11:35] [Server thread/TRACE] [Forge/Forge]: Sending event FMLServerStoppedEvent to mod Forge
[00:11:35] [Server thread/TRACE] [Forge/Forge]: Sent event FMLServerStoppedEvent to mod Forge
[00:11:35] [Server thread/DEBUG] [FML/]: Bar Step: ServerStopped - Minecraft Forge took 0,000s
[00:11:35] [Server thread/TRACE] [bagginses/bagginses]: Sending event FMLServerStoppedEvent to mod bagginses
[00:11:35] [Server thread/TRACE] [bagginses/bagginses]: Sent event FMLServerStoppedEvent to mod bagginses
[00:11:35] [Server thread/DEBUG] [FML/]: Bar Step: ServerStopped - Bagginses took 0,000s
[00:11:35] [Server thread/ERROR] [BiomesOPlenty/]: Skipping event FMLServerStoppedEvent and marking errored mod BiomesOPlenty since required dependency Forge has errored
[00:11:35] [Server thread/DEBUG] [FML/]: Bar Step: ServerStopped - Biomes O' Plenty took 0,001s
[00:11:35] [Server thread/ERROR] [chiselsandbits/]: Skipping event FMLServerStoppedEvent and marking errored mod chiselsandbits since required dependency Forge has errored
[00:11:35] [Server thread/DEBUG] [FML/]: Bar Step: ServerStopped - Chisels & Bits took 0,001s
[00:11:35] [Server thread/TRACE] [fastleafdecay/fastleafdecay]: Sending event FMLServerStoppedEvent to mod fastleafdecay
[00:11:35] [Server thread/TRACE] [fastleafdecay/fastleafdecay]: Sent event FMLServerStoppedEvent to mod fastleafdecay
[00:11:35] [Server thread/DEBUG] [FML/]: Bar Step: ServerStopped - Fast Leaf Decay took 0,000s
[00:11:35] [Server thread/ERROR] [forestry/]: Skipping event FMLServerStoppedEvent and marking errored mod forestry since required dependency Forge has errored
[00:11:35] [Server thread/DEBUG] [FML/]: Bar Step: ServerStopped - Forestry took 0,001s
[00:11:35] [Server thread/ERROR] [JEI/]: Skipping event FMLServerStoppedEvent and marking errored mod JEI since required dependency Forge has errored
[00:11:35] [Server thread/DEBUG] [FML/]: Bar Step: ServerStopped - Just Enough Items took 0,000s
[00:11:35] [Server thread/ERROR] [Quark/]: Skipping event FMLServerStoppedEvent and marking errored mod Quark since required dependency Forge has errored
[00:11:35] [Server thread/DEBUG] [FML/]: Bar Step: ServerStopped - Quark took 0,001s
[00:11:35] [Server thread/TRACE] [randomthings/randomthings]: Sending event FMLServerStoppedEvent to mod randomthings
[00:11:35] [Server thread/TRACE] [randomthings/randomthings]: Sent event FMLServerStoppedEvent to mod randomthings
[00:11:35] [Server thread/DEBUG] [FML/]: Bar Step: ServerStopped - Random Things took 0,000s
[00:11:35] [Server thread/TRACE] [xreliquary/xreliquary]: Sending event FMLServerStoppedEvent to mod xreliquary
[00:11:35] [Server thread/TRACE] [xreliquary/xreliquary]: Sent event FMLServerStoppedEvent to mod xreliquary
[00:11:35] [Server thread/DEBUG] [FML/]: Bar Step: ServerStopped - Reliquary took 0,000s
[00:11:35] [Server thread/DEBUG] [FML/]: Bar Finished: ServerStopped took 0,004s
[00:11:35] [Server thread/INFO] [FML/]: The state engine was in incorrect state ERRORED and forced into state SERVER_STOPPED. Errors may have been discarded.
[00:11:35] [Server thread/INFO] [FML/]: The state engine was in incorrect state ERRORED and forced into state AVAILABLE. Errors may have been discarded.

```

**Comment by Alrawn** [comment] 2016-06-06 10:29
a workaround seems to be disabling forge's recipe sorter, so I'm unsure if this isn't some conflicting recipe issue.

**Comment by MrAmericanMike** [comment] 2016-06-06 20:18
Similar if not the same problem here. I have a pack with some mods, as soon as I add Forestry the pack crashes. Forestry itself works ok on a separate instance, but not sure in here, what the conflict could be.

http://pastebin.com/4khMJitM

Creating a new World just stucks at 0%

PS: Also in my case, as Alrawn said, disabling Forge recipe sorter solved the issue.

**Comment by mezz** [comment] 2016-06-06 22:41
I probably need to add Forestry's recipes to the sorter. Not sure why it matters, since they inherit from vanilla recipes. Let's see what happens. I'll let you know when it's up and available.

**Comment by mezz** [comment] 2016-06-07 02:01
Pushed a fix, it should be up in 5 minutes or so.

**Comment by mezz** [comment] 2016-06-07 04:02
Let me know if this fixes the problem for you and I can close the issue.

**Comment by Alrawn** [comment] 2016-06-07 15:22
I'll test once I'm back from work, THX.

**Comment by Alrawn** [comment] 2016-06-07 23:13
tested the fix. recipeSorter works, server starts and doesnt crash when I join, so it looks like this fixed it.

**Comment by mezz** [comment] 2016-06-08 00:10
Cool, thanks.

**Closed as completed by mezz** 2016-06-08 00:10 UTC
Labels: Bug-major

**Comment by cjburkey01** [comment] 2016-06-25 03:33
This is happening again.  Here's the crash: [Github GIST](https://gist.github.com/cjburkey01/4dde1c3d1a6c7508ace2510ae18a281c).

(I am using Forestry 1.10-5.1.3.182 with Forge 12.18.0.1986-1.10.0)

Specifically when creating a world in singleplayer, I haven't tested on servers.

**Comment by mezz** [comment] 2016-06-25 03:34
That is from another mod, Forestry's recipes are being sorted properly now.

**Comment by mezz** [comment] 2016-06-25 03:35
See https://github.com/MinecraftForge/MinecraftForge/issues/2962, this crash can be caused by any mod that does not register its recipes with the sorter. It may be a Forge issue.

**Comment by cjburkey01** [comment] 2016-06-25 03:35
I'll see if I can figure it out.  Thanks.
