### ISSUE TITLE
[suggestion]Let raintank automatically output water

### ISSUE THREAD

**Issue by wormzjl** [ForestryMC/ForestryMC#1250] opened 2016-05-26 14:41 UTC
hope this thing didn't get forgotten :P
Also might consider to make it produce water faster?

**Comment by mezz** [comment] 2016-05-26 17:15
Not forgotten. Dupe of https://github.com/ForestryMC/ForestryMC/issues/955
I want to add a fluid handler capability to Forge soon, and that should make this easier to implement.

I don't think it should produce water faster, you can always make more of them. With auto-output it should be pretty easy to set up.

**Closed as completed by mezz** 2016-05-26 17:15 UTC
Labels: duplicate

**Comment by wormzjl** [comment] 2016-05-26 18:34
Oh my memory sucks XD
