### ISSUE TITLE
1.12.1 Adding a dirty controller to a world that has no registered controllers!

### ISSUE THREAD

**Issue by dmodoomsirius** [ForestryMC/ForestryMC#1828] opened 2017-08-27 05:30 UTC
https://gist.github.com/dmodoomsirius/f2b0922c4b83d25b65d6f69b5bf27482

Minecraft version 1.12.1
Forge Version 14.22.0.2456
Forestry version 5.5.0.169

**Comment by Nedelosk** [comment] 2017-08-28 14:09
Duplicate of #1132

**Closed as completed by Nedelosk** 2017-08-28 14:09 UTC
Labels: duplicate
