### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by NavedNoor** [ForestryMC/ForestryMC#2369] opened 2019-02-18 21:25 UTC
The server crashed after placing the Multifarm Blocks and trying to access it. Server stops when you try to join, can't play anymore. Have a look at the crash log:
https://gist.github.com/NavedNoor/4030dcea50905ef07a1bc337759345e5

**Comment by temp1011** [comment] 2019-02-18 21:27
Duplicate of https://github.com/ForestryMC/ForestryMC/issues/2340? Updating should fix this.

**Closed as completed** 2019-02-19 15:48 UTC
