### ISSUE TITLE
incompatibility with BetterWithMods

### ISSUE THREAD

**Issue by GanjaManNL** [ForestryMC/ForestryMC#2498] opened 2019-12-01 22:04 UTC
with the mod, BetterWithMods if u punch a tree with just a fist it drops bark, are you guys able to make something so it uses an axe if you put it in the tree farm?

**Comment by Nedelosk** [comment] 2020-02-26 18:08
Duplicate of #2499

**Closed as completed by Nedelosk** 2020-02-26 18:08 UTC
Labels: duplicate
