### ISSUE TITLE
Server Crash on Startup

### ISSUE THREAD

**Issue by drewbit** [ForestryMC/ForestryMC#1321] opened 2016-06-14 00:05 UTC
On booting the world I get the following error:

http://pastebin.com/GRceyK2T

Forestry Version: forestry_1.9.4-5.0.12.154

**Comment by mezz** [comment] 2016-06-14 00:30
Thanks for the report!
This is a duplicate of https://github.com/ForestryMC/ForestryMC/issues/1318
It is fixed in the latest version.

**Closed as completed by mezz** 2016-06-14 00:30 UTC
Labels: duplicate
