### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by THEVOLCO** [ForestryMC/ForestryMC#539] opened 2015-03-04 15:36 UTC
I updated forestry and now my game crahes when i try to Launch it.

Crash Report:

http://pastebin.com/d3FxRbjG

**Comment by mezz** [comment] 2015-03-04 23:59
Thanks for the report!
This is a dupe of issue #269, please see that issue for the workaround.

**Closed by mezz** 2015-03-04 23:59 UTC
