### ISSUE TITLE
Strange information in console

### ISSUE THREAD

**Issue by Xee1** [ForestryMC/ForestryMC#648] opened 2015-05-04 15:08 UTC
Hi, with latest version of Forestry, I get this in console:

[17:01:44] [Client thread/INFO] [BuildCraft]: Starting BuildCraft 6.4.14
[17:01:44] [Client thread/INFO] [BuildCraft]: Copyright (c) SpaceToad, 2011-2015
[17:01:44] [Client thread/INFO] [BuildCraft]: http://www.mod-buildcraft.com
**[17:01:45] [Client thread/INFO] [Forestry]: Module BuildCraft 6 Transport Plugin failed to load: BuildCraft|Transport not found**

But I've Buildcraft 6(See the lines below), it's normal?

**Comment by Nirek-K** [comment] 2015-05-04 20:44
Duplicate of #613, fixed in #614.

**Closed by Nirek-K** 2015-05-04 20:44 UTC
Labels: Duplicate

**Comment by Xee1** [comment] 2015-05-04 20:51
Thanks, sorry for duplicate issue.
