### ISSUE TITLE
NEI Crash with Forestry 4.0.8.36

### ISSUE THREAD

**Issue by Ayrrow** [ForestryMC/ForestryMC#886] opened 2015-10-13 03:08 UTC
Full Log - http://paste.ee/p/ILI0g line 1138 onwards.

Loaded up a creative world, got this crash almost immediately after hitting 'R' for recipe on forestry wrench by accident. Immediately crash on world load after attempting again.

**Comment by mezz** [comment] 2015-10-13 04:03
Thanks for the report! 
This is a duplicate of https://github.com/ForestryMC/ForestryMC/issues/873
NEI Integration has an updated version that works with Forestry 4.

**Closed as completed by mezz** 2015-10-13 04:03 UTC
Labels: duplicate, compat

**Comment by Ayrrow** [comment] 2015-10-13 04:04
Ahh I missed that somehow. Thanks, and sorry for that.
