### ISSUE TITLE
Duplicating items in analyzers

### ISSUE THREAD

**Issue by CAJIO** [ForestryMC/ForestryMC#1044] opened 2016-01-16 18:03 UTC
Duplication algorithm:
- Take 64 analyzer units (stack)
- Open analyzer gui
- Put inside the things that you want to analyze
- Close gui
- Spread analyzers in you inventory

Now you can open analyzers one by one and get stored item from each of it.

This can be fixed by making the analyzers not stackable.

**Comment by mezz** [comment] 2016-01-16 20:06
Thanks for the report!
Have you tried with the latest version? It should be fixed already.
Duplicate of #1008

**Closed as completed by mezz** 2016-01-16 20:06 UTC
Labels: duplicate
