### ISSUE TITLE
Crash on Savegame load: forestry_1.10.2-5.2.7.220

### ISSUE THREAD

**Issue by MokahTGS** [ForestryMC/ForestryMC#1377] opened 2016-08-05 23:42 UTC
Getting a crash loading a savegame:

http://pastebin.com/mMYwkawq

**Comment by CovertJaguar** [comment] 2016-08-06 00:27
Possible duplicate of #1368

Try updating to the latest version.

**Comment by Nedelosk** [comment] 2016-08-06 01:25
He uses the last version: forestry{5.2.7.220} (forestry_1.10.2-5.2.7.220.jar)

**Comment by MokahTGS** [comment] 2016-08-06 01:28
Yup...it is the latest version

**Comment by MokahTGS** [comment] 2016-08-06 01:36
Would removing TESLA temporarily fix this issue?

**Comment by mezz** [comment] 2016-08-06 04:21
This is the opposite problem, your TESLA is out of date :).
It should work if you update it to Tesla-1.10.2-1.2.1.42
https://minecraft.curseforge.com/projects/tesla/files

**Closed as completed** 2016-08-06 06:44 UTC
Labels: Not Forestry, Power, Not a Bug
