### ISSUE TITLE
Really minor rendering bug 

### ISSUE THREAD

**Issue by estebes** [ForestryMC/ForestryMC#777] opened 2015-07-29 14:05 UTC
The brick farm valve gets a random texture when the multiblock is completed. (forestry_1.7.10-3.7.0.639-unstable)
http://i.imgur.com/eXZzJed.png

**Comment by mezz** [comment] 2015-07-30 00:05
Thanks for the report!
This is fixed in the 4.0 unstable. Dupe of #747

**Closed as completed by mezz** 2015-07-30 00:05 UTC
Labels: duplicate
