### ISSUE TITLE
Leaf Textures Missing and machine blocks replacing some leaves.

### ISSUE THREAD

**Issue by Herekar** [ForestryMC/ForestryMC#2093] opened 2018-04-19 13:36 UTC
I just recently updated a modpack some friends and i are working on and we  restarted our server with a brand new world gen and had some issues with forestry trees and there leaves.  We are in MC version 1.12.2 with forge version 14.23.3.2669 and forestry version 5.8.0.267 if you need info on what other mods we have here is a link to the mod pack page https://minecraft.curseforge.com/projects/herekars-test-pack.
![thermleaves](https://user-images.githubusercontent.com/10598786/38994302-faf6ed80-43b3-11e8-937b-8e8f33eecc0a.png)
![morethermleaves](https://user-images.githubusercontent.com/10598786/38994366-30225170-43b4-11e8-8c18-a6e562eb0a54.png)
![misstextandraintanks](https://user-images.githubusercontent.com/10598786/38994381-3c1b6282-43b4-11e8-9f01-5e3a6179e602.png)

**Comment by bookerthegeek** [comment] 2018-04-19 19:44
Your mod load order changed it looks like.

**Comment by Nedelosk** [comment] 2018-04-20 13:08
Duplicate of #1543

**Closed as completed** 2018-05-11 09:07 UTC
Labels: duplicate
