### ISSUE TITLE
Incompatibility with ModTweaker and MineTweaker [Forestry 4.0]

### ISSUE THREAD

**Issue by Filvandrel** [ForestryMC/ForestryMC#850] opened 2015-09-27 15:15 UTC
https://gist.github.com/mezz/3237b128bef899aea4c6

**Comment by liach** [comment] 2015-09-27 15:19
Ask ModTweaker author to upgrade. `at modtweaker2.mods.forestry.Forestry.(Forestry.java:17)`

**Comment by Filvandrel** [comment] 2015-09-27 15:29
I've deleted ModTweaker, and got this:

https://gist.github.com/mezz/01197491956fc69905a6

**Comment by Nirek-K** [comment] 2015-09-27 18:52
That 2nd one is the same as issue 849.

**Comment by mezz** [comment] 2015-09-27 23:19
Dupe of #849: Reika's DragonAPI is not compatible with Forestry 4.0 beta yet.

**Comment by mezz** [comment] 2015-09-28 00:11
Actually leaving this open for the first crash, with ModTweaker/MineTweaker as part of the crash.

**Comment by mezz** [comment] 2015-10-12 16:27
ModTweaker is working on an update: https://github.com/jaredlll08/ModTweaker2/issues/252

**Comment by mezz** [comment] 2015-10-13 04:07
ModTweaker has a pre-release version available here: https://github.com/Voidi/ModTweaker2/releases/tag/0.9.5

**Closed as completed by mezz** 2015-10-13 04:07 UTC
Labels: compat
