### ISSUE TITLE
[1.10.2] Forestry Swarms seem to use a lot of tick time

### ISSUE THREAD

**Issue by ghost** [ForestryMC/ForestryMC#1415] opened 2016-09-04 09:43 UTC
https://timings.aikar.co/v2/?id=ff4746d8caf0472795f9c1c4400b734c&section=all

It can be seen in this report under `Minecraft::world - tileEntityTick`

**Comment by ghost** [comment] 2016-09-04 11:34
New report here: https://timings.aikar.co/v2/?id=b9c4ea317ef44381a47da05d58af0882&section=lag#546_1

**Comment by CovertJaguar** [comment] 2016-09-04 14:13
They also account for two-thirds of your tile entities. No surprise they are the largest consumer of tick time. 

This does however suggest that some kind of "hibernation" mode might be in order when no players are nearby. Possibly even removing/replacing with a non-ticking version when it's not absolutely needed. Random block ticks could be used to determine if more resolution is needed and swap in the Tile Entity.

**Comment by ghost** [comment] 2016-09-04 23:43
Would it be possible to disable the bee swarms in the meantime as a config option? It's having quite a big impact on our server performance. 

Thanks!

**Comment by CovertJaguar** [comment] 2016-09-05 09:04
Actually looking at the code, they probably could be implemented entirely using block ticks.

Either way, it's pretty important that no world gen tile entity ticks. The shear number just kills performance of the ticking tile entity list (because it's a stinking ArrayList).

**Comment by ghost** [comment] 2016-09-05 09:15
That would certainly be ideal.

**Comment by Nirek-K** [comment] 2016-09-05 09:27
(Mezz is on vacation until labor day)

**Comment by mezz** [comment] 2016-09-07 08:15
Thanks for the report!
I'm having difficulty interpreting the report you posted. 
`[+]Minecraft::tickTileEntity - forestry.Swarm` seems to be misnamed, there are all kinds of unrelated things under it if you expand it.

**Comment by mezz** [comment] 2016-09-07 08:29
In my own testing, the performance impact looks extremely small:
![tilehive](https://cloud.githubusercontent.com/assets/916092/18305045/88c917ea-749a-11e6-96d2-7289fa96c4de.png)

**Comment by CovertJaguar** [comment] 2016-09-07 10:25
Swarm is the String label for [TileHive.java](https://github.com/ForestryMC/ForestryMC/blob/mc-1.10/src/main/java/forestry/apiculture/tiles/TileHive.java). The things under it are probably other mods responding to events, they use very little of the total time. The problem is that there are 3,600 hives in his world. (hive ticks / total ticks). Which asides from having a general negative affect on all operations that manipulate Tile Entities (because ArrayList/Mojang), they massively outnumber all other tile entities.

I'm somewhat unclear on whether TileHive refers to Alveries or world gen hives...

**Comment by mezz** [comment] 2016-09-07 10:50
Yep, "forestry.Swarm" == `TileHive` == worldgen hive. There are separate tiles for "forestry.Alveary", "forestry.apiary", and "forestry.bee_house".

I don't understand how a server can have 3,600 of them loaded at once, that seems incorrect. There are far fewer than one worldgen hive per chunk.

**Comment by ghost** [comment] 2016-09-07 11:09
I think Sponge or Forge may be having issues with unloading chunks. I've removed the update() code in TileHive for now and they are no longer on the timings.

**Comment by mezz** [comment] 2016-09-07 21:46
Please try without Sponge.

**Comment by Nedelosk** [comment] 2016-10-19 12:43
I think this is fixed with #1470.

**Comment by mezz** [comment] 2016-10-19 20:51
CovertJaguar still has a good point, I'll see if I can make them use block updates instead of ticking tile entities, to avoid clogging the tile entity list.

**Comment by mezz** [comment] 2016-10-19 21:03
Not really possible to do and keep the bee effects. I think the performance is good enough for now that bees aren't auto-loading new chunks and creating crazy numbers of ticking hives, we'll see if there are any more performance complaints.

**Closed as completed by mezz** 2016-10-19 21:03 UTC
Labels: enhancement, bees
