### ISSUE TITLE
crash on server, Terraqueous related

### ISSUE THREAD

**Issue by knoxhack** [ForestryMC/ForestryMC#1357] opened 2016-07-17 02:28 UTC
https://gist.github.com/knoxhack/271d8c4056d51e98cf9678d52cab9970

**Comment by CovertJaguar** [comment] 2016-07-17 02:36
Not sure if this is Forestry or not, but it seems it may be related to #1355.

**Comment by Nedelosk** [comment] 2016-07-17 09:02
Thanks for the report!
This is not a bug of forestry. The proplem are the terraqueous leves.

**Comment by CovertJaguar** [comment] 2016-07-17 10:22
@Nedelosk I'm not convinced that's true. Not after seeing the same error twice in as many days for different "trees". Especially since one would expect "net.minecraft.block.BlockHugeMushroom" to not be bugged like this. (Issue #1344)

**Comment by knoxhack** [comment] 2016-07-17 10:32
The Terraqueous dev said he will add a code so this don't happen. http://minecraft.curseforge.com/projects/terraqueous/issues/10

**Comment by Nedelosk** [comment] 2016-07-17 10:40
Ok it's true, it is a bug of forestry, It is fixed in the next version. Sorry

**Comment by CovertJaguar** [comment] 2016-07-17 10:40
He also said 

> EntityButterfly is passing the state of another block.
> In this case its 'asking' BlockTreeFoliageCB if its leaves yet giving it the blockstate of one of the logs.

Which makes this very much a Forestry problem.

**Comment by Nedelosk** [comment] 2016-07-17 10:44
@knoxhack I think I have fixed it. Can you please test it ?

**Comment by CovertJaguar** [comment] 2016-07-17 11:03
d7f063eec8917d358b5e225be07ca73b79bd532f

**Comment by mezz** [comment] 2016-07-22 05:13
This appears to be fixed.

**Closed as completed by mezz** 2016-07-22 05:13 UTC
Labels: Bug-major, Butterflys
