### ISSUE TITLE
Continued crashing with Engineer's Life

### ISSUE THREAD

**Issue by Elderwolf569** [ForestryMC/ForestryMC#2505] opened 2019-12-26 05:02 UTC
Thank you for reporting!

This is the crash log. States that Forestry is the likely suspect. Crashes as soon as it tries to load the terrain. Issues started occurring while mining. Anamoly appeared from an unknown mined ore. found its way into my inventory and crashed ever since. Fairly far into the progression of the game towards the end of the industrial revolution.

--- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2019-12-26 12:37:15 AWST
Description: Unexpected error

java.lang.IllegalArgumentException: Cannot set property PropertyEnum{name=resource, clazz=class forestry.core.blocks.EnumResourceType, values=[APATITE, COPPER, TIN]} to BRONZE on block forestry:resources, it is not an allowed value
    at pl.asie.foamfix.common.FoamyBlockState.withProperty(FoamyBlockState.java:59)
    at forestry.core.blocks.BlockResourceOre.getStateFromMeta(BlockResourceOre.java:60)
    at forestry.core.blocks.BlockResourceOre.getNameFromMeta(BlockResourceOre.java:126)
    at forestry.core.items.ItemBlockForestry.getTranslationKey(ItemBlockForestry.java:60)
    at net.minecraft.item.Item.getUnlocalizedNameInefficiently(Item.java:292)
    at net.minecraft.item.Item.getItemStackDisplayName(Item.java:362)
    at net.minecraft.item.ItemStack.getDisplayName(ItemStack.java:617)
    at net.minecraftforge.client.GuiIngameForge.renderToolHighlight(GuiIngameForge.java:648)
    at net.minecraftforge.client.GuiIngameForge.renderGameOverlay(GuiIngameForge.java:172)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1098)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected level --
  Level name: MpServer
  All players: 1 total; [EntityPlayerSP['Elderwolf569'/72, l='MpServer', x=-0.64, y=33.00, z=50.59]]
  Chunk stats: MultiplayerChunkCache: 0, 0
  Level seed: 0
  Level generator: ID 06 - OTG, ver 0. Features enabled: false
  Level generator options: 
  Level spawn location: World: (0,64,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Level time: 10801582 game time, 15625040 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
  Forced entities: 1 total; [EntityPlayerSP['Elderwolf569'/72, l='MpServer', x=-0.64, y=33.00, z=50.59]]
  Retry entities: 0 total; []
  Server brand: fml,forge
  Server type: Integrated singleplayer server

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 8.1 (amd64) version 6.3
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 907804320 bytes (865 MB) / 2805465088 bytes (2675 MB) up to 3008888832 bytes (2869 MB)
  JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3228m -Xms256m -XX:PermSize=256m
  IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
  FML: MCP 9.42 Powered by Forge 14.23.5.2838 129 mods loaded, 129 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                            | Version                  | Source                                            | Signature                                |
       |:------ |:----------------------------- |:------------------------ |:------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft                     | 1.12.2                   | minecraft.jar                                     | None                                     |
       | LCHIJA | mcp                           | 9.42                     | minecraft.jar                                     | None                                     |
       | LCHIJA | FML                           | 8.0.99.99                | forge-1.12.2-14.23.5.2838.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                         | 14.23.5.2838             | forge-1.12.2-14.23.5.2838.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | itemphysic                    | 1.4.0                    | minecraft.jar                                     | None                                     |
       | LCHIJA | ivtoolkit                     | 1.3.3-1.12               | minecraft.jar                                     | None                                     |
       | LCHIJA | otgcore                       | 1.12.2 - v7              | minecraft.jar                                     | None                                     |
       | LCHIJA | openmodscore                  | 0.12.2                   | minecraft.jar                                     | None                                     |
       | LCHIJA | foamfixcore                   | 7.7.4                    | minecraft.jar                                     | None                                     |
       | LCHIJA | akashictome                   | 1.2-12                   | AkashicTome-1.2-12.jar                            | None                                     |
       | LCHIJA | crafttweaker                  | 4.1.19                   | CraftTweaker2-1.12-4.1.19.jar                     | None                                     |
       | LCHIJA | mtlib                         | 3.0.6                    | MTLib-3.0.6.jar                                   | None                                     |
       | LCHIJA | modtweaker                    | 4.0.17                   | modtweaker-4.0.17.jar                             | None                                     |
       | LCHIJA | jei                           | 4.15.0.289               | jei_1.12.2-4.15.0.289.jar                         | None                                     |
       | LCHIJA | ctm                           | MC1.12.2-0.3.3.22        | CTM-MC1.12.2-0.3.3.22.jar                         | None                                     |
       | LCHIJA | chisel                        | MC1.12.2-0.2.1.35        | Chisel-MC1.12.2-0.2.1.35.jar                      | None                                     |
       | LCHIJA | mantle                        | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                          | None                                     |
       | LCHIJA | tinkersextras                 | 1.12.2-1.0.9             | TinkersExtras-1.12.2-1.0.9.jar                    | b02331787272ec3515ebe63ecdeea0d746653468 |
       | LCHIJA | tweakersconstruct             | 1.12.2-1.5.1             | tweakersconstruct-1.12.2-1.5.1.jar                | None                                     |
       | LCHIJA | twilightforest                | 3.9.984                  | twilightforest-1.12.2-3.9.984-universal.jar       | None                                     |
       | LCHIJA | tconstruct                    | 1.12.2-2.12.0.157        | TConstruct-1.12.2-2.12.0.157.jar                  | None                                     |
       | LCHIJA | immersiveengineering          | 0.12-91                  | ImmersiveEngineering-0.12-91.jar                  | 4cb49fcde3b43048c9889e0a3d083225da926334 |
       | LCHIJA | alternatingflux               | 0.12.2-2                 | alternatingflux-0.12.2-2.jar                      | None                                     |
       | LCHIJA | applecore                     | 3.2.0                    | AppleCore-mc1.12.2-3.2.0.jar                      | None                                     |
       | LCHIJA | reborncore                    | 3.16.2.473               | RebornCore-1.12.2-3.16.2.473-universal.jar        | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
       | LCHIJA | techreborn                    | 2.24.1.1032              | TechReborn-1.12.2-2.24.1.1032-universal.jar       | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
       | LCHIJA | betterwithmods                | 1.12-2.3.20-1027         | BetterWithMods-1.12-2.3.20-1027.jar               | None                                     |
       | LCHIJA | appleskin                     | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                        | None                                     |
       | LCHIJA | quark                         | r1.6-177                 | Quark-r1.6-177.jar                                | None                                     |
       | LCHIJA | autoreglib                    | 1.3-32                   | AutoRegLib-1.3-32.jar                             | None                                     |
       | LCHIJA | betteradvancements            | 0.1.0.77                 | BetterAdvancements-1.12.2-0.1.0.77.jar            | None                                     |
       | LCHIJA | betterbuilderswands           | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar   | None                                     |
       | LCHIJA | betterquesting                | 3.5.311                  | BetterQuesting-3.5.311.jar                        | None                                     |
       | LCHIJA | betterwithengineering         | 1.2                      | BetterWithEngineering-1.6.jar                     | None                                     |
       | LCHIJA | betterwithlib                 | ${version}               | BetterWithLib-1.12-1.5.jar                        | None                                     |
       | LCHIJA | bibliocraft                   | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar                 | None                                     |
       | LCHIJA | openterraingenerator          | v6                       | OpenTerrainGenerator-1.12.2 - v6.jar              | e9f7847a78c5342af5b0a9e04e5abc0b554d69e0 |
       | LCHIJA | biomebundle                   | 5.1                      | Biome_Bundle-1.12.2-v6.1.jar                      | None                                     |
       | LCHIJA | ceramics                      | 1.12-1.3.7               | Ceramics-1.12-1.3.7.jar                           | None                                     |
       | LCHIJA | chameleon                     | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                          | None                                     |
       | LCHIJA | chancecubes                   | 1.12.2-4.1.0.300         | ChanceCubes-1.12.2-4.1.0.300.jar                  | None                                     |
       | LCHIJA | conarm                        | 1.2.4                    | conarm-1.12.2-1.2.4.jar                           | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
       | LCHIJA | controlling                   | 3.0.7                    | Controlling-3.0.7.jar                             | None                                     |
       | LCHIJA | cookingforblockheads          | 6.4.71                   | CookingForBlockheads_1.12.2-6.4.71.jar            | None                                     |
       | LCHIJA | ctgui                         | 1.0.0                    | CraftTweaker2-1.12-4.1.19.jar                     | None                                     |
       | LCHIJA | crafttweakerjei               | 2.0.3                    | CraftTweaker2-1.12-4.1.19.jar                     | None                                     |
       | LCHIJA | creeperconfetti               | 1.4.2                    | creeperconfetti-1.4.2.jar                         | None                                     |
       | LCHIJA | cucumber                      | 1.1.3                    | Cucumber-1.12.2-1.1.3.jar                         | None                                     |
       | LCHIJA | custommainmenu                | 2.0.9                    | CustomMainMenu-MC1.12.2-2.0.9.jar                 | None                                     |
       | LCHIJA | forestry                      | 5.8.2.394                | forestry_1.12.2-5.8.2.394.jar                     | None                                     |
       | LCHIJA | divergentunderground          | 0.64.0                   | Divergent-Underground-1.12-0.64.0.jar             | None                                     |
       | LCHIJA | dungeontactics                | DT-0.16.6                | DungeonTactics-1.12.2-0.16.6.jar                  | None                                     |
       | LCHIJA | endercore                     | 1.12.2-0.5.69            | EnderCore-1.12.2-0.5.69.jar                       | None                                     |
       | LCHIJA | enderio                       | 5.1.51                   | EnderIO-base-1.12.2-5.1.51.jar                    | None                                     |
       | LCHIJA | enderiobase                   | 5.1.51                   | EnderIO-base-1.12.2-5.1.51.jar                    | None                                     |
       | LCHIJA | enderioconduits               | 5.1.51                   | EnderIO-conduits-1.12.2-5.1.51.jar                | None                                     |
       | LCHIJA | enderiopowertools             | 5.1.51                   | EnderIO-conduits-1.12.2-5.1.51.jar                | None                                     |
       | LCHIJA | refinedstorage                | 1.6.15                   | refinedstorage-1.6.15.jar                         | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
       | LCHIJA | enderioconduitsrefinedstorage | 5.1.51                   | EnderIO-conduits-refinedstorage-1.12.2-5.1.51.jar | None                                     |
       | LCHIJA | enderiointegrationforestry    | 5.1.51                   | EnderIO-integration-forestry-1.12.2-5.1.51.jar    | None                                     |
       | LCHIJA | exchangers                    | 1.12.2-2.8               | Exchangers-1.12.2-2.8.jar                         | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
       | LCHIJA | externaltweaker               | 0.3                      | externaltweaker-1.12-0.3.jar                      | None                                     |
       | LCHIJA | minerva                       | 1.0.13                   | minerva-library-1.0.13.jar                        | b851b8b7c7f4d8d0e910ff27618150ba80c026ec |
       | LCHIJA | extraalchemy                  | 0.5.1                    | extraalchemy-0.5.1.jar                            | b851b8b7c7f4d8d0e910ff27618150ba80c026ec |
       | LCHIJA | fastleafdecay                 | v14                      | FastLeafDecay-v14.jar                             | None                                     |
       | LCHIJA | fastbench                     | 1.7.2                    | FastWorkbench-1.12.2-1.7.2.jar                    | None                                     |
       | LCHIJA | foamfix                       | 0.10.5-1.12.2            | foamfix-0.10.5-1.12.2.jar                         | None                                     |
       | LCHIJA | ftblib                        | 5.4.3.123                | FTBLib-5.4.3.123.jar                              | None                                     |
       | LCHIJA | ftbutilities                  | 5.4.0.99                 | FTBUtilities-5.4.0.99.jar                         | None                                     |
       | LCHIJA | ftbbackups                    | 0.0.0.ftbbackups         | FTBUtilitiesBackups-1.0.0.4.jar                   | None                                     |
       | LCHIJA | waila                         | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                       | None                                     |
       | LCHIJA | immersivecables               | 1.3.2                    | ImmersiveCables-1.12.2-1.3.2.jar                  | None                                     |
       | LCHIJA | immersivepetroleum            | 1.1.9                    | immersivepetroleum-1.12.2-1.1.9.jar               | None                                     |
       | LCHIJA | immersivetech                 | 1.3.10                   | immersivetech-1.12-1.3.10.jar                     | None                                     |
       | LCHIJA | infernalmobs                  | 1.7.6                    | InfernalMobs-1.12.2.jar                           | None                                     |
       | LCHIJA | inventorytweaks               | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                          | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCHIJA | ironbackpacks                 | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar                 | None                                     |
       | LCHIJA | ironchest                     | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar                   | None                                     |
       | LCHIJA | jeibees                       | 0.9.0.5                  | jeibees-0.9.0.5-mc1.12.2.jar                      | None                                     |
       | LCHIJA | journeymap                    | 1.12.2-5.5.5             | journeymap-1.12.2-5.5.5.jar                       | None                                     |
       | LCHIJA | jeresources                   | 0.9.2.60                 | JustEnoughResources-1.12.2-0.9.2.60.jar           | None                                     |
       | LCHIJA | levelup2                      | ${version}               | Level Up! 2-1.1.23-1.12.jar                       | None                                     |
       | LCHIJA | libraryex                     | 1.0.11                   | LibraryEx-1.12.2-1.0.11.jar                       | None                                     |
       | LCHIJA | login_shield                  | 1.12.2-3-g7c6e7ac        | Login_Shield-1.12.2-3-g7c6e7ac.jar                | None                                     |
       | LCHIJA | lunatriuscore                 | 1.2.0.42                 | LunatriusCore-1.12.2-1.2.0.42-universal.jar       | None                                     |
       | LCHIJA | moartinkers                   | 0.6.0                    | moartinkers-0.6.0.jar                             | None                                     |
       | LCHIJA | mousetweaks                   | 2.10                     | MouseTweaks-2.10-mc1.12.2.jar                     | None                                     |
       | LCHIJA | netherportalfix               | 5.3.17                   | NetherPortalFix_1.12.1-5.3.17.jar                 | None                                     |
       | LCHIJA | nmsot                         | 1.2.2-mc1.12.2           | NoMobSpawningOnTrees-1.2.2-mc1.12.2.jar           | None                                     |
       | LCHIJA | openmods                      | 0.12.2                   | OpenModsLib-1.12.2-0.12.2.jar                     | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | LCHIJA | openblocks                    | 1.8.1                    | OpenBlocks-1.12.2-1.8.1.jar                       | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | LCHIJA | oreexcavation                 | 1.4.140                  | OreExcavation-1.4.140.jar                         | None                                     |
       | LCHIJA | patchouli                     | 1.0-20                   | Patchouli-1.0-20.jar                              | None                                     |
       | LCHIJA | pickletweaks                  | 2.1.3                    | PickleTweaks-1.12.2-2.1.3.jar                     | None                                     |
       | LCHIJA | portablecrafting              | @VERSION@                | PortableCrafting-1.12.2-1.0.2.jar                 | None                                     |
       | LCHIJA | potioncore                    | 1.8_for_1.12.2           | PotionCore-1.8_for_1.12.2.jar                     | None                                     |
       | LCHIJA | questbook                     | 3.1.1-1.12               | questbook-3.1.1-1.12.jar                          | None                                     |
       | LCHIJA | reccomplex                    | 1.4.8.2                  | RecurrentComplex-1.4.8.2.jar                      | None                                     |
       | LCHIJA | repurpose                     | 1.0.0.19                 | Repurpose-1.0.0.19.jar                            | None                                     |
       | LCHIJA | resourceloader                | 1.5.3                    | ResourceLoader-MC1.12.1-1.5.3.jar                 | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCHIJA | signals                       | 1.4.1-30                 | Signals-1.12.2-1.4.1-30-universal.jar             | None                                     |
       | LCHIJA | soundfilters                  | 0.11_for_1.12            | SoundFilters-0.11_for_1.12.jar                    | None                                     |
       | LCHIJA | spiceoflife                   | 1.3.12                   | SpiceOfLife-mc1.12-1.3.12.jar                     | None                                     |
       | LCHIJA | stackie                       | 1.6.0.48                 | Stackie-1.12.2-1.6.0.48-universal.jar             | None                                     |
       | LCHIJA | bq_standard                   | 3.4.167                  | StandardExpansion-3.4.167.jar                     | None                                     |
       | LCHIJA | stepup                        | 1.0.2-mc1.10-1.12.2      | StepUp-1.0.2-mc1.10-1.12.jar                      | None                                     |
       | LCHIJA | storagedrawers                | 1.12.2-5.4.0             | StorageDrawers-1.12.2-5.4.0.jar                   | None                                     |
       | LCHIJA | surge                         | 2.0.77                   | Surge-1.12.2-2.0.77.jar                           | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | thebomplugin                  | 1.12-0.2.3               | thebomplugin-1.12-0.2.3.jar                       | None                                     |
       | LCHIJA | tinkeredhegemony              | @VERSION@                | TinkeredHegemony-0.2.1.jar                        | None                                     |
       | LCHIJA | tcomplement                   | 1.12.2-0.4.2             | TinkersComplement-1.12.2-0.4.2.jar                | None                                     |
       | LCHIJA | tinkersjei                    | 1.2                      | tinkersjei-1.2.jar                                | None                                     |
       | LCHIJA | tinkertoolleveling            | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar               | None                                     |
       | LCHIJA | tombmanygraves                | 1.12-4.2.0               | TombManyGraves-1.12-4.2.0.jar                     | None                                     |
       | LCHIJA | vanillafix                    | 1.0.10-SNAPSHOT          | VanillaFix-1.0.10-99.jar                          | None                                     |
       | LCHIJA | vanillafoodpantry             | 4.3.1                    | vanillafoodpantry-mc1.12.2-4.3.1.jar              | None                                     |
       | LCHIJA | variedcommodities             | 1.12.2                   | VariedCommodities_1.12.2(15may18.jar              | None                                     |
       | LCHIJA | vials                         | 1.2.1.5                  | Vials-MC1.12-1.2.1.5.jar                          | None                                     |
       | LCHIJA | vc                            | 5.9.13                   | ViesCraft-1.12.2-5.9.13.jar                       | None                                     |
       | LCHIJA | vtweaks                       | 2.0.4                    | VTweaks-1.12.2-2.0.4.jar                          | None                                     |
       | LCHIJA | waterstrainer                 | 3.2.0                    | WaterStrainer-1.12-3.2.0.jar                      | None                                     |
       | LCHIJA | wawla                         | 2.5.273                  | Wawla-1.12.2-2.5.273.jar                          | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | waystones                     | 4.0.72                   | Waystones_1.12.2-4.0.72.jar                       | None                                     |
       | LCHIJA | worldprimer                   | 0.5.0                    | worldprimer-1.12.2-0.5.0.jar                      | 2b03e1423915a189b8094816baa18f239d576dff |
       | LCHIJA | orelib                        | 3.5.2.2                  | OreLib-1.12.2-3.5.2.2.jar                         | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | reauth                        | 3.6.0                    | reauth-3.6.0.jar                                  | daba0ec4df71b6da841768c49fb873def208a1e3 |
       | LCHIJA | survivalist                   | 2.1.6                    | Survivalist-1.12.2-2.1.6.jar                      | None                                     |
       | LCHIJA | techreborn_compat             | 1.0.0                    | TechReborn-ModCompatibility-1.12.2-1.3.2.60.jar   | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
       | LCHIJA | primal_tech                   | 0.3.4                    | PrimalTech-0.3.4.jar                              | None                                     |
  Loaded coremods (and transformers): Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      Quark Plugin (Quark-r1.6-177.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
                                        squeek.applecore.asm.TransformerModuleHandler
                                      OTGCorePlugin (OTG-Core.jar)
                                        com.pg85.otg.forge.asm.OTGClassTransformer
                                      OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
                                        openmods.core.OpenModsClassTransformer
                                      CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      LoadingPlugin (BetterWithLib-1.12-1.5.jar)
                                        betterwithmods.library.core.ClassTransformer
                                      Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      EnderCorePlugin (EnderCore-1.12.2-0.5.69-core.jar)
                                        com.enderio.core.common.transform.EnderCoreTransformer
                                        com.enderio.core.common.transform.SimpleMixinPatcher
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
                                        lumien.resourceloader.asm.ClassTransformer
                                      SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
                                        
                                      IELoadingPlugin (ImmersiveEngineering-core-0.12-91.jar)
                                        blusunrize.immersiveengineering.common.asm.IEClassTransformer
                                      IvToolkit (IvToolkit-1.3.3-1.12.jar)
                                        
                                      ItemPatchingLoader (ItemPhysic Lite 1.3.7 mc1.12.2.jar)
                                        com.creativemd.itemphysic.ItemTransformer
  GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.2.12422 Compatibility Profile Context 13.152.1.1000' Renderer: 'AMD Radeon (TM) HD ON (TM) HD + HD 8570D Dual Graphics'
  OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - wailaIntegration (Enabled/Not Forced)
  Pulsar/tcomplement loaded Pulses: - ModuleCommons (Enabled/Forced)
                                    - ModuleMelter (Enabled/Not Forced)
                                    - ModuleArmor (Enabled/Not Forced)
                                    - ModuleSteelworks (Enabled/Not Forced)
                                    - CeramicsPlugin (Enabled/Not Forced)
                                    - ChiselPlugin (Enabled/Not Forced)
                                    - ToolLevelingPlugin (Enabled/Not Forced)
                                    - Oredict (Enabled/Forced)
  RebornCore: Plugin Engine: 0
              RebornCore Version: 3.16.2.473
              Runtime Debofucsation 1
              RenderEngine: 0
  Ender IO: No known problems detected.
            
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            !!!You are looking at the diagnostics information, not at the crash.       !!!
            !!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  forestry : Modules have been disabled in the config: Crate
  Suspected Mods: FoamFix (foamfix), Forestry (forestry)
  Launched Version: forge-14.23.5.2838
  LWJGL: 2.9.4
  OpenGL: AMD Radeon (TM) HD ON (TM) HD + HD 8570D Dual Graphics GL version 4.2.12422 Compatibility Profile Context 13.152.1.1000, ATI Technologies Inc.
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: faithful-1-12-2-3d-stuff-e3270.zip, Soartex_Fanver_Modded_Universal.zip
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 4x AMD A8-6500 APU with Radeon(tm) HD Graphics
  Client Crashes Since Restart: 1
  Integrated Server Crashes Since Restart: 0

For issues:
 * Try the latest version, it may have fixed the issue already.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.

**Comment by ZeekDaGeek** [comment] 2020-01-04 02:07
I'm also having this issue, I attempted to remove foam fix and the error moves to just Vanilla classes.

```
 java.lang.IllegalArgumentException: Cannot set property PropertyEnum{name=resource, clazz=class forestry.core.blocks.EnumResourceType, values=[APATITE, COPPER, TIN]} to BRONZE on block forestry:resources, it is not an allowed value
  7     at net.minecraft.block.state.BlockStateContainer$StateImplementation.withProperty(BlockStateContainer.java:227)
  8     at forestry.core.blocks.BlockResourceOre.getStateFromMeta(BlockResourceOre.java:60)
  9     at forestry.core.blocks.BlockResourceOre.getNameFromMeta(BlockResourceOre.java:126)
 10     at forestry.core.items.ItemBlockForestry.getTranslationKey(ItemBlockForestry.java:60)
 11     at net.minecraft.item.ItemStack.getTranslationKey(ItemStack.java:509)
 12     at net.minecraft.entity.item.EntityItem.getName(EntityItem.java:419)
 13     at net.minecraft.entity.Entity.toString(Entity.java:2505)
 14     at java.lang.String.valueOf(String.java:2994)
 15     at java.lang.StringBuilder.append(StringBuilder.java:131)
 16     at zabi.minecraft.minerva.common.capability.SimpleCapability$CapabilityEventListener.onEntityTracking(SimpleCapability.java:522)
 17     at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1309_CapabilityEventListener_onEntityTracking_StartTracking.invoke(.dynamic)
 18     at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
 19     at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
 20     at net.minecraftforge.event.ForgeEventFactory.onStartEntityTracking(ForgeEventFactory.java:400)
 21     at net.minecraft.entity.EntityTrackerEntry.updatePlayerEntity(EntityTrackerEntry.java:460)
 22     at net.minecraft.entity.EntityTracker.sendLeashedEntitiesInChunk(EntityTracker.java:392)
 23     at net.minecraft.server.management.PlayerChunkMapEntry.sendToPlayers(PlayerChunkMapEntry.java:162)
 24     at net.minecraft.server.management.PlayerChunkMap.tick(SourceFile:165)
 25     at net.minecraft.world.WorldServer.tick(WorldServer.java:227)
 26     at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756)
 27     at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397)
 28     at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
 29     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
 30     at java.lang.Thread.run(Thread.java:748)

```

**Comment by Nedelosk** [comment] 2020-02-15 09:59
Duplicate of #2502

**Closed as completed by Nedelosk** 2020-02-15 09:59 UTC
