### ISSUE TITLE
GAME CRASH WITH LAST 2 UPDATES

### ISSUE THREAD

**Issue by toticorrea** [ForestryMC/ForestryMC#910] opened 2015-10-24 03:22 UTC
Same crash ocurred when I start the game with last 2 versions of Forestry. Once I go back to the 3.6.9.28 version everything is fine.

CRASH LOG:

https://gist.github.com/mezz/85a32c53aa21c7de48eb

**Comment by erkro1** [comment] 2015-10-24 12:56
I believe 769 should fix that
http://ic2api.player.to:8080/job/Forestry_Dev/769/

**Comment by mezz** [comment] 2015-10-24 23:06
Thanks for the report! 
This is a duplicate of #871

Please update BoP, they have a new version that is compatible with Forestry 4 here: http://files.minecraftforge.net/BiomesOPlenty/.

**Closed as completed by mezz** 2015-10-24 23:06 UTC
Labels: duplicate, compat
