### ISSUE TITLE
Forestry generates trees with random parts

### ISSUE THREAD

**Issue by ghost** [ForestryMC/ForestryMC#1922] opened 2017-12-22 17:56 UTC
Here's a fun one: 

On my server there "trees" scattered throughout the world made of various forestry parts. Most of the time it's oak planks or slabs as the "trunk" and then a forestry item such as the centrifuge for the "leaves". Being around these "trees" causes the leaves to duplicate all over the place and the only way to stop it is to go in creative, destroy the oak slabs, and then destroy everything until it stops duplicating. 

Similar thing is happening with lumber Mills and honey. Honey waterfalls everywhere with a lumber Mills at the center.

**Comment by temp1011** [comment] 2017-12-31 18:12
https://github.com/ForestryMC/ForestryMC/issues/1543?

**Comment by ghost** [comment] 2017-12-31 18:17
Looks like it. Just restarted the server for the first time so I'll hop on and see if things broke.

**Comment by Nedelosk** [comment] 2018-01-06 16:35
Duplicate of #1543.

**Closed as completed by Nedelosk** 2018-01-06 16:35 UTC
Labels: Bug-major, duplicate
