### ISSUE TITLE
Moved to forestry 3.6.10.1 and 4.1.1 to immediately Crash. (DragonAPI)

### ISSUE THREAD

**Issue by kostay99** [ForestryMC/ForestryMC#959] opened 2015-11-09 00:40 UTC
Actually that's the problem: http://pastebin.com/WZXuNb2H
I do not know how to solve it.

**Comment by ghost** [comment] 2015-11-09 00:51
Forestry itself isn't crashing, Rotarycraft and Chromaticraft are erroring out when registering mutations it seems. If this doesn't happen with 3.6.x and only with 4.x it could be an API problem from them adding mutations and not using the 4.x API stuff. That's what it looks like to me but I'm not experienced with this. (and especially inexperienced with those two mods and what they add)

@kostay99 Test it out by removing those two and see if it still crashes. Once you determine which mods are causing this, I'll leave it to others who know more than myself to explain whether the fix is on their end or someone else's.

**Comment by mezz** [comment] 2015-11-09 02:52
Thanks for the report!
Reika's DragonAPI is not compatible with Forestry 4 yet.

Dupe of https://github.com/ForestryMC/ForestryMC/issues/849

Reika is aware of the issue https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/229

**Closed as completed by mezz** 2015-11-09 02:52 UTC
Labels: duplicate, compat
