### ISSUE TITLE
Error starting server (Farseek)

### ISSUE THREAD

**Issue by CraftYourWay** [ForestryMC/ForestryMC#1309] opened 2016-06-09 06:50 UTC
when i start my server i get this:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  IC2core (industrialcraft-2-2.5.6-ex19.jar)
  StreamsCoreMod (Streams-1.9.4-0.2.jar)
  TransformerLoader (OpenComputers-MC1.9.4-1.6.0.1-beta.2.jar)
  CodeChickenCorePlugin (CodeChickenCore-1.9.4-2.0.2.64-universal.jar)
  CCCDeobfPlugin (unknown)
  FarseekCoreMod (Farseek-1.9.4-1.0.jar)
  CCLCorePlugin (CodeChickenLib-1.9.4-2.0.2.38-universal.jar)
  EnderCorePlugin (EnderCore-1.9.4-0.4.0.23-alpha.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 6/9/16 8:44 AM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderException: java.lang.NoSuchMethodError: forestry.core.proxy.ProxyRender.getRendererAnalyzer()Lnet/minecraft/client/renderer/tileentity/TileEntitySpecialRenderer;
    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:179)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:590)
    at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:93)
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:320)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:118)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:429)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: forestry.core.proxy.ProxyRender.getRendererAnalyzer()Lnet/minecraft/client/renderer/tileentity/TileEntitySpecialRenderer;
    at forestry.core.blocks.BlockTypeCoreTesr.<clinit>(BlockTypeCoreTesr.java:25)
    at forestry.core.blocks.BlockRegistryCore.<init>(BlockRegistryCore.java:33)
    at forestry.core.PluginCore.registerItemsAndBlocks(PluginCore.java:114)
    at forestry.plugins.PluginManager.runSetup(PluginManager.java:221)
    at forestry.Forestry.preInit(Forestry.java:90)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:566)
    at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:228)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:206)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:587)
    ... 5 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.9.4
    Operating System: Linux (amd64) version 3.16.0-71-generic
    Java Version: 1.8.0_91, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 2769789448 bytes (2641 MB) / 4119330816 bytes (3928 MB) up to 4119330816 bytes (3928 MB)
    JVM Flags: 2 total; -Xms4096M -Xmx4096M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.28 Powered by Forge 12.17.0.1954 36 mods loaded, 36 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCH mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCH FML{8.0.99.99} [Forge Mod Loader](forge.jar) 
    UCH Forge{12.17.0.1954} [Minecraft Forge](forge.jar) 
    UCH CodeChickenCore{2.0.2.64} [CodeChicken Core](minecraft.jar) 
    UCH OpenComputers|Core{1.6.0.1-beta.2} [OpenComputers (Core)](minecraft.jar) 
    UCH AutoSapling{1.3.2} [AutoSapling](AutoSapling-1.3.2-MC1.9.4.jar) 
    UCH BBG{5.0.0} [BetterBedrockGen](BBG-1.9.4-5.0.0.jar) 
    UCH BiomesOPlenty{4.1.0.2025} [Biomes O' Plenty](BiomesOPlenty-1.9.4-4.1.0.2025-universal.jar) 
    UCH Chameleon{1.9-2.1.4} [Chameleon](Chameleon-1.9-2.1.4.jar) 
    UCH ChickenChunks{2.0.2.31} [ChickenChunks](ChickenChunks-1.9.4-2.0.2.31-universal.jar) 
    UCH shadowmc{3.3.6} [ShadowMC](ShadowMC-1.9.4-3.3.6.jar) 
    UCH DiscordChat{1.2.1} [DiscordChat](DiscordChat-1.9.4-1.2.1.jar) 
    UCH endercore{1.9.4-0.4.0.23-alpha} [EnderCore](EnderCore-1.9.4-0.4.0.23-alpha.jar) 
    UCH Waila{1.7.0} [Waila](Waila-1.7.0-B3_1.9.4.jar) 
    UCH EnderIO{1.9.4-3.0.0.38_alpha} [Ender IO](EnderIO-1.9.4-3.0.0.38_alpha.jar) 
    UCH EnderStorage{2.0.2.52} [EnderStorage](EnderStorage-1.9.4-2.0.2.52-universal.jar) 
    UCH Farseek{1.9.4} [Farseek](Farseek-1.9.4-1.0.jar) 
    UCH IC2{2.5.6-ex19} [IndustrialCraft 2](industrialcraft-2-2.5.6-ex19.jar) 
    UCH JEI{3.6.2.211} [Just Enough Items](jei_1.9.4-3.6.2.211.jar) 
    UCE forestry{5.0.10.147} [Forestry](forestry_1.9.4-5.0.10.147.jar) 
    UCH netherportalfix{1.0} [Nether Portal Fix](netherportalfix-mc1.9.4-4.0.1.jar) 
    UCH ObsidianPlates{1.1.1} [Obsidian Plates](ObsidianPlates-1.1.1_1.9.4.jar) 
    UCH OpenComputers{1.6.0.1-beta.2} [OpenComputers](OpenComputers-MC1.9.4-1.6.0.1-beta.2.jar) 
    UCH ProjectE{1.9.4-PE1.0.1B} [ProjectE](ProjectE-1.9.4-PE1.0.1B.jar) 
    UCH refinedstorage{0.7.8} [Refined Storage](refinedstorage-0.7.8.jar) 
    UCH xreliquary{1.9.4-1.3.2.372} [Reliquary](Reliquary-1.9.4-1.3.2.372.jar) 
    UCH Signals{1.0} [Signals](Signals-1.9.4-0.1.1-universal.jar) 
    UCH simplyconveyors{1.7.10-1.0.0} [Simply Conveyors](SimplyConveyors-1.0.3.jar) 
    UCH StellarAPI{0.4.3.2b} [Stellar API](Stellar API-0.4.3.2b.jar) 
    UCH stellarsky{0.4.4.1} [Stellar Sky](Stellar Sky-0.4.4.1.jar) 
    UCH StorageDrawers{1.9-3.1.7} [Storage Drawers](StorageDrawers-1.9-3.1.7.jar) 
    UCH Streams{1.9.4} [Streams](Streams-1.9.4-0.2.jar) 
    UCH thutcore{3.1.2} [ThutCore](thutcore-1.9.4-3.1.2.jar) 
    UCH thuttech{3.0.2} [Thut's Tech](thuttech-3.0.2.jar) 
    UCH WailaHarvestability{1.1.7} [Waila Harvestability](WailaHarvestability-mc1.9-1.1.7.jar) 
    UCH worldedit{6.1.2} [WorldEdit](worldedit-forge-mc1.9-6.1.2-dist.jar) 
    Loaded coremods (and transformers): 
IC2core (industrialcraft-2-2.5.6-ex19.jar)

StreamsCoreMod (Streams-1.9.4-0.2.jar)
  streams.core.StreamsClassTransformer
TransformerLoader (OpenComputers-MC1.9.4-1.6.0.1-beta.2.jar)
  li.cil.oc.common.asm.ClassTransformer
CodeChickenCorePlugin (CodeChickenCore-1.9.4-2.0.2.64-universal.jar)
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
CCCDeobfPlugin (unknown)

FarseekCoreMod (Farseek-1.9.4-1.0.jar)
  farseek.core.FarseekClassTransformer
CCLCorePlugin (CodeChickenLib-1.9.4-2.0.2.38-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
EnderCorePlugin (EnderCore-1.9.4-0.4.0.23-alpha.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
    EnderIO: No known problems detected.
    Profiler Position: N/A (disabled)
    Is Modded: Definitely; Server brand changed to 'fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by mezz** [comment] 2016-06-09 07:34
Thanks for the report!
This is a duplicate of https://github.com/ForestryMC/ForestryMC/issues/1248

This is a problem with Farseek.
Please subscribe to the Farseek issue here: delvr/Farseek#10

**Closed as completed by mezz** 2016-06-09 07:34 UTC
Labels: duplicate
