### ISSUE TITLE
Vegetable Farm

### ISSUE THREAD

**Issue by noruma** [ForestryMC/ForestryMC#2098] opened 2018-04-22 14:02 UTC
I am doing 1.12.2 but trying to attach iron tube with a soldering iron to make carrots and potatoes in multi farm,
I could not do it. Even in other vacuum tubes, what seems to have changed has been changed, but has there been a change in the new version?

**Comment by Nedelosk** [comment] 2018-04-22 15:43
Duplicate of #1970

**Closed as completed by Nedelosk** 2018-04-22 15:43 UTC
Labels: duplicate
