### ISSUE TITLE
Unable to create Genome

### ISSUE THREAD

**Issue by Orcinuss** [ForestryMC/ForestryMC#1536] opened 2016-12-14 01:28 UTC
Players are trying to get started with bees and the server crashes as soon as the Queen is created.

Crash Report: http://pastebin.com/EPK9uZ0F
Forestry: 5.2.16.331

**Comment by Nedelosk** [comment] 2017-01-01 03:20
Has anyone else this bug, if not I will close this.

**Comment by mezz** [comment] 2017-01-01 07:33
I think this has the same root cause as https://github.com/ForestryMC/ForestryMC/issues/1524

**Closed as completed** 2017-04-05 12:43 UTC
