### ISSUE TITLE
[1.9.4] Random crashes from world gen with BoP

### ISSUE THREAD

**Issue by jawsawn** [ForestryMC/ForestryMC#1270] opened 2016-06-03 11:03 UTC
https://gist.github.com/JAWSAWN/6c571036fd94e8578fc9dbfa44473508

It sometimes crashes to desktop while generating a new world.
Also could randomly happen while generating new chunks.

latest forge, latest forestry and latest BoP

**Comment by GirafiStudios** [comment] 2016-06-03 11:06
Duplicate of https://github.com/ForestryMC/ForestryMC/issues/1260 . It's actually a problem with Biomes O' Plenty and is already reported to the author :)

**Comment by mezz** [comment] 2016-06-03 11:06
Thanks for the report!
We are aware of this problem, please see https://github.com/Glitchfiend/BiomesOPlenty/issues/763
Duplicate of https://github.com/ForestryMC/ForestryMC/issues/1260

**Closed as completed** 2016-06-03 11:06 UTC
Labels: duplicate

**Comment by mezz** [comment] 2016-06-03 15:07
This turned out to be a Forge issue MinecraftForge/MinecraftForge#2941
