### ISSUE TITLE
1.10.2 crash with IE wooden storage crates

### ISSUE THREAD

**Issue by rstone7** [ForestryMC/ForestryMC#1852] opened 2017-09-17 14:50 UTC
I've been using version 1.10.2-5.2.17.376 in the Coop Life pack, which also has Immersive Engineering.  Today I had a freezing issue when trying to open an IE Wooden Storage Crate which was full of bees; I hadn't thought much of it, since I'd been using crates to store bees for a while now and hadn't had any problem (and my other bee crate was fine), but later (having replaced the crate and the princesses that were in the buggy one) I was trying to use the replacement crate and got this error and crashed to the main page: "Internal Exception: java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes".  A quick google revealed that this error message has been previously linked to Iron Backpacks and Forestry Bees, so I figured I should let you guys know as well as IE.

Not sure if the log has any useful information, since I didn't crash to launcher, but I've attached the relevant bits anyway.

(https://gist.github.com/rstone7/2237a73f4d6af279a2e922c59c50c1f4)

**Comment by mezz** [comment] 2017-09-17 22:58
Thanks for the report!
Please report this to IE. Forestry bees contain a lot of NBT data and that is probably the cause of the issue, but other mods should be able to handle it without crashing.

**Comment by Nedelosk** [comment] 2018-01-05 14:56
This is a  Immersive Engineerin bug and was fixed in 1.12 but not in 1.10.2 #2403.

**Closed as completed by Nedelosk** 2018-01-05 14:56 UTC
Labels: Not Forestry
