### ISSUE TITLE
Long missing purple-black particals

### ISSUE THREAD

**Issue by 3TUSK** [ForestryMC/ForestryMC#1307] opened 2016-06-09 02:26 UTC
Steps to reproduce:
1. Install latest Forestry (5.0.10.147)
2. Free fall from high place onto some Forestry blocks.
Example:
![2016-06-09_10 06 43](https://cloud.githubusercontent.com/assets/9113033/15916975/afa4a142-2e2a-11e6-9d0b-6c68fd998ae6.png)
![2016-06-09_10 07 34](https://cloud.githubusercontent.com/assets/9113033/15916976/afad024c-2e2a-11e6-81e9-79fb66252809.png)
![2016-06-09_10 07 49](https://cloud.githubusercontent.com/assets/9113033/15916978/afaf0d1c-2e2a-11e6-8865-be8a7132b885.png)
![2016-06-09_10 09 46](https://cloud.githubusercontent.com/assets/9113033/15916977/afaebab0-2e2a-11e6-8e7f-c018f30373a8.png)
![2016-06-09_10 13 20](https://cloud.githubusercontent.com/assets/9113033/15916992/cde59daa-2e2a-11e6-8f4e-2c1a41fa7bca.png)

While things like stamp collector are fine:
![2016-06-09_10 09 53](https://cloud.githubusercontent.com/assets/9113033/15916988/c41f33da-2e2a-11e6-9108-3d7c116865b0.png)

Further test shows that any blocks in Forestry that is not whole cube except wooden stairs and slabs will have the problem above. Hope I am correct.
Do note that vanilla chest has a wood plank fx when player falling on.

**Comment by mezz** [comment] 2016-06-09 02:29
Thanks! This is a duplicate of https://github.com/ForestryMC/ForestryMC/issues/1200

**Comment by 3TUSK** [comment] 2016-06-09 02:30
Ok I should have spent more time on searching... I though it havent been reported.

**Closed as completed by mezz** 2016-06-09 02:29 UTC
Labels: duplicate

**Comment by mezz** [comment] 2016-06-09 02:30
No problem, better to have it reported too many times than not reported at all.
