### ISSUE TITLE
Beehives not stinging

### ISSUE THREAD

**Issue by Daihok41** [ForestryMC/ForestryMC#2361] opened 2019-02-02 05:36 UTC
Not sure if this is bug or not but Arent the beehives suppost to sting you when you get near them? I tryed setting gamemode to normal in the forestry config but that didnt change anything. For some reason the hives are not stinging me when near them.

Using version 1.12.2-5.8.2.382

**Comment by Nedelosk** [comment] 2019-02-02 11:31
Duplicate of #2289

**Closed as completed by Nedelosk** 2019-02-02 11:31 UTC
Labels: duplicate
