### ISSUE TITLE
Help me plz game crach

### ISSUE THREAD

**Issue by MoonGhost18** [ForestryMC/ForestryMC#2513] opened 2020-01-16 10:44 UTC
[game crash report 3.txt](https://github.com/ForestryMC/ForestryMC/files/4070746/game.crash.report.3.txt)

I have no idea what to do but forestry is metioned so i was thinking you might know!!!

**Comment by inspiiree** [comment] 2020-01-29 20:17
Same issue here, this is the crash report I get (server)
https://pastebin.com/raw/gusXrBgV

**Comment by Nedelosk** [comment] 2020-02-15 10:17
Duplicate of https://github.com/ForestryMC/Binnie/issues/626

**Closed as completed by Nedelosk** 2020-02-15 10:17 UTC
Labels: Not Forestry
