### ISSUE TITLE
Strange multifarm behavior (1.7.10, forestry 3.3.0.6)

### ISSUE THREAD

**Issue by Vic3Dexe** [ForestryMC/ForestryMC#487] opened 2015-01-30 09:36 UTC
Tried a max size multifarm. Results (can't attach images, old firefox etc):
http://i.imgur.com/rDUJo3g.jpg
http://i.imgur.com/z0uM7p4.png
http://i.imgur.com/zgPZAG9.jpg
http://i.imgur.com/bZIM3gP.jpg
http://i.imgur.com/fjiKUwi.jpg

Bricks around farm represents neighbor farms.
If I break wrong-placed humus, it placed again. It will replace for example water blocks and sugar cane from neighbor farms, but not cobble.

Tried with other mods and without (only forge multipart etc).
No glitch, no crash, just... this.
Do you need fml log?

**Comment by Vic3Dexe** [comment] 2015-01-30 09:36
ps forge 10.13.2.1286

**Comment by Sandriell** [comment] 2015-01-30 12:29
The sizes for multi-farms changed recently. The smallest size with a 3x3 core is now 21 blocks wide. If I recall correctly, the formula is something like "2* (x * 3) + x", where "x" is the width of your central structure.

**Comment by mezz** [comment] 2015-01-31 04:41
Thanks for the report!
I think this is a duplicate of issue #251. I'll put it higher on the todo list.

**Closed by mezz** 2015-01-31 04:41 UTC
