### ISSUE TITLE
Forestry electrical engine and buildcraft wooden kinetic pipes wont connect

### ISSUE THREAD

**Issue by Grimreepr** [ForestryMC/ForestryMC#1786] opened 2017-08-07 04:57 UTC
I have the engine powered, it is producing and storing RF, but the electrical engine will NOT connect to a Buildcraft wooden Kinetic pipe.  Buildcraft engines hook up just fine, Forestry electrical engine will not connect.  It just sits there building and storing RF.  I tried connecting it directly to  Buildcraft quarry with the same effect.  No power transferred to machine or wooden kinetic pipe.

Mods in use are Forge ( of course) Minecraft v1.11.2
IC2 for 1.11.2
JEi for 1.11.2
Buildcraft for 1.11.2
Code chicken core for 1.11.2 and chicken chunks for 1.11.2

**Comment by 3TUSK** [comment] 2017-08-07 10:11
Buildcraft for 1.11.2 generates and consumes MJ.

**Comment by LuigiHutch** [comment] 2017-08-07 21:31
Duplicate of https://github.com/ForestryMC/ForestryMC/issues/1691

**Closed as completed** 2017-10-16 21:57 UTC
Labels: duplicate
