### ISSUE TITLE
Beekeeper house issue

### ISSUE THREAD

**Issue by Ryukossei** [ForestryMC/ForestryMC#1433] opened 2016-09-22 17:32 UTC
Im not sure where I would find the error for as this is happening from server side of everything, but every time anyone on my brothers server goes near any village that may contain a beekeepers house, the entire server crashes and shuts down. When the server comes back up, it sees to have corrected itself to a point. The village will now load however, the house where the beekeeper would be is not there, it is just an empty space with a forestry fence. We are not sure what is going on with this error. My brother got ahold of another mod maker thinking that it might have been thier mod, when they messaged back on how to fix a bug in their config files for thier mod, they had suggested that we get in contact with the Forestry Mod people. I hope we can resolve this fast. I like the tree breeding and would like to be able to continue the work on it.

**Comment by mezz** [comment] 2016-09-22 19:44
Thanks for the report!
Please paste the crash log from the server to https://gist.github.com and link it here.

**Comment by Ryukossei** [comment] 2016-09-22 21:04
https://gist.github.com/Ryukossei/ea7849e3df24885cd5f32dae97e1e979

**Comment by Ryukossei** [comment] 2016-09-22 21:04
Sorry wasnt at home when you replied.

**Comment by mezz** [comment] 2016-09-22 21:07
No problem.
This is a duplicate of https://github.com/ForestryMC/ForestryMC/issues/1124
Just delete the `apiculture.cfg` file in the `/config/forestry/` folder and it should fix itself next time you start the server.

**Comment by Ryukossei** [comment] 2016-09-22 21:09
ok

**Comment by mezz** [comment] 2016-09-22 22:23
Did that fix the issue?

**Comment by Ryukossei** [comment] 2016-09-23 01:11
Trying now. Is it going to the bees from the game?

**Comment by Ryukossei** [comment] 2016-09-23 01:12
Remove

**Comment by Ryukossei** [comment] 2016-09-23 01:24
Yeah it worked. Thank you very much!

**Closed as completed** 2016-09-29 05:21 UTC
Labels: duplicate
