### ISSUE TITLE
Crash when opening machine GUI on Forge 1370+

### ISSUE THREAD

**Issue by cram42** [ForestryMC/ForestryMC#628] opened 2015-04-17 15:12 UTC
When right-clicking still, squeezer, etc.
Crash below:

[01:06:10] [Client thread/FATAL]: Unreported exception thrown!
java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:29) ~[FluidStack.class:?]
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:59) ~[FluidStack.class:?]
	at forestry.core.fluids.TankManager.processGuiUpdate(TankManager.java:232) ~[TankManager.class:?]
	at forestry.core.gui.ContainerLiquidTanks.func_75137_b(ContainerLiquidTanks.java:90) ~[ContainerLiquidTanks.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147245_a(NetHandlerPlayClient.java:1151) ~[bjb.class:?]
	at net.minecraft.network.play.server.S31PacketWindowProperty.func_148833_a(SourceFile:26) ~[gp.class:?]
	at net.minecraft.network.play.server.S31PacketWindowProperty.func_148833_a(SourceFile:9) ~[gp.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) ~[bje.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1590) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_40]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_40]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_40]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]

**Comment by Drakray** [comment] 2015-04-17 22:37
Same crash
http://pastebin.com/PndNmPLK

**Comment by mezz** [comment] 2015-04-17 23:04
Thanks for the report!
This is a duplicate of #604
Please use the latest unstable build of Forestry if you are using the latest Forge. Forestry 3.5.3 works with the "recommended" version of Forge.
I will probably fix it soon so that the any build will work with any Forge.

**Closed by mezz** 2015-04-17 23:04 UTC

**Comment by cram42** [comment] 2015-04-18 02:01
Oh my goodness. I'm such a noob. I downloaded the latest unstable build, but installed a previous jar!
