### ISSUE TITLE
Some Woods Not Showing

### ISSUE THREAD

**Issue by ghost** [ForestryMC/ForestryMC#1623] opened 2017-03-11 18:33 UTC
![2017-03-11_21 31 18](https://cloud.githubusercontent.com/assets/24831406/23825818/e4383d36-0699-11e7-88e8-c44fef7a2e9b.png)
it is amazing.
and it's same with mapple wood, maybe all woods in forestry. using forge 2255, latest forestry.

**Comment by MauveCloud** [comment] 2017-03-11 18:51
The logs in the background reveal you're using Better Foliage, meaning this is a duplicate of https://github.com/octarine-noise/BetterFoliage/issues/117

**Comment by ghost** [comment] 2017-03-11 20:08
ah yes, i am.  so it is compatibility issue. waiting for fix then ^^

**Closed as completed** 2017-03-12 04:37 UTC
Labels: duplicate
