### ISSUE TITLE
When carrying two Miner's backpack, the resources get doubled

### ISSUE THREAD

**Issue by fabioluissilva** [ForestryMC/ForestryMC#1025] opened 2015-12-29 16:02 UTC
When carrying two miner's backpack when mining, the resources that I mine get doubled. I was extremely happy when I saw that in one backpack I had 12 diamonds, but then when I checked the other one, it had also 12 diamonds that I didn't mine.

Minecraft on OSX 1.7.10 + IC2 + Buildcraft + Forestry 4.2.3.51

**Comment by mezz** [comment] 2015-12-29 17:30
Thanks for the report!
Duplicate of #1008

**Closed as completed by mezz** 2015-12-29 17:30 UTC
Labels: duplicate
