### ISSUE TITLE
Wortable consuming GT items when shift clicked recipe from NEI

### ISSUE THREAD

**Issue by JasonMcRay** [ForestryMC/ForestryMC#751] opened 2015-07-06 14:06 UTC
When i shift-click the recipe containing GT Tools from NEI into worktable and I try to craft the item, it will fully consume the tools.

**Steps to reproduce:**
1) Find a recipe for any Pickaxe Head
2) Shift+click on question mark near to put ghost items into worktable layout
3) Put necessary items in the storage place
4) Craft the Pickaxe Head
5) Both tools will dissapear, they should only take a damage.

On top of this issue, there is a sound issue if I put required items in the storage place. It will play hammering sound in loop as long as the recipe can be crafted.

**Comment by mezz** [comment] 2015-07-07 04:01
Thanks for the clear report!
This is a known issue, but I didn't know it effects GregTech, I'll make fixing it a higher priority.
Dupe of https://github.com/ForestryMC/ForestryMC/issues/680

I think the sound issue could be a problem on their side, but we'll only know for sure once I fix the other issues.

**Closed as completed by mezz** 2015-07-07 04:01 UTC
Labels: duplicate
