### ISSUE TITLE
NBT data lost

### ISSUE THREAD

**Issue by ResponsibleBear** [ForestryMC/ForestryMC#1083] opened 2016-02-27 16:23 UTC
Hello. Just watch the video.
Carpenter and worktable bug.
Forestry version 4.2.9.57
https://www.youtube.com/watch?v=iNBBJo8wX_M&feature=youtu.be

**Comment by mezz** [comment] 2016-02-29 08:17
Thanks for the report!
I am not able to reproduce this issue with nbt items. Which Gregtech are you using, so I can try it?

**Comment by ResponsibleBear** [comment] 2016-02-29 08:51
Hey there. 
GregTech version is 5.09.19. 
From here http://forum.industrial-craft.net/index.php?page=Thread&threadID=11488

**Comment by BoOmka** [comment] 2016-08-06 08:14
Gregtech 5.09.22. All GT tools still lose their data.
http://imgur.com/a/BnSYn

That bug works ONLY IN MULTIPLAYER!
Singleplayer works fine.

**Comment by Nedelosk** [comment] 2017-07-23 23:11
The video is unavailable and I don't think that we will ever fix this so I close this.

**Closed as completed by Nedelosk** 2017-07-23 23:11 UTC
Labels: Bug-major, 1.7 or under
