### ISSUE TITLE
Stuck on 1.7.10-3.6.6.24 version

### ISSUE THREAD

**Issue by DadYoshi** [ForestryMC/ForestryMC#1024] opened 2015-12-28 20:27 UTC
Server wont start when I try 1.7.10-4.2.3.51

Here is crash rpt
[crash-2015-12-28_15.14.02-server.txt](https://github.com/ForestryMC/ForestryMC/files/73527/crash-2015-12-28_15.14.02-server.txt)

**Comment by mezz** [comment] 2015-12-28 20:47
Thanks for the report!
Duplicate of https://github.com/ForestryMC/ForestryMC/issues/857

**Closed as completed by mezz** 2015-12-28 20:47 UTC
Labels: duplicate, compat
