### ISSUE TITLE
[1.10.2-5.2.8.234] Cables randomly disconnect from the Bio Generators.

### ISSUE THREAD

**Issue by marcin212** [ForestryMC/ForestryMC#1401] opened 2016-08-18 19:09 UTC
Cables (from  ic2) randomly disconnect  from the Bio Generators. Destroying the cables doesn't help, only replacing the machine solves the problem. Sometimes this happens after a server restart, sometimes after a chunk reload.

https://img.bymarcin.com/screenshot-2016-08-18_20-57-54.png
- industrialcraft-2-2.6.26-ex110
- forestry_1.10.2-5.2.8.234
- forge-1.10.2-12.18.1.2056

**Comment by mezz** [comment] 2016-08-18 21:10
Thanks for the report!
@sfPlayer1 do you have any idea why this might happen? I haven't changed the Bio Generator code in a long time, so it may need to be updated somehow.

**Comment by Player3324** [comment] 2016-08-18 23:19
I'd tentatively say the issue is on our (IC2's) side.

Is the cable also functionally disconnected or just visually?

**Comment by marcin212** [comment] 2016-08-18 23:20
Cable is disconnected  functionally and visually.

**Comment by mezz** [comment] 2016-10-21 07:16
I'm closing this as an IC2 issue until they have resolved this bug:
 http://bt.industrial-craft.net/view.php?id=1959

If that gets fixed and this issue still occurs, we can reopen this issue or create a new one.

**Closed as completed by mezz** 2016-10-21 07:16 UTC
Labels: Not Forestry
