### ISSUE TITLE
Crash on launching

### ISSUE THREAD

**Issue by JonathanPlovie** [ForestryMC/ForestryMC#2161] opened 2018-06-15 08:16 UTC
[crash-2018-06-15_10.13.51-server.txt](https://github.com/ForestryMC/ForestryMC/files/2105289/crash-2018-06-15_10.13.51-server.txt)

Forge 1.12.2-14.2.3.4.2705
forestry 1.12.2-5.8.0.296

**Comment by Nedelosk** [comment] 2018-06-15 08:21
Duplicate of #2160.

**Closed as completed by Nedelosk** 2018-06-15 08:21 UTC
