### ISSUE TITLE
Exception trying to process over a phase

### ISSUE THREAD

**Issue by Coolfeather2** [ForestryMC/ForestryMC#1788] opened 2017-08-08 05:33 UTC
**I am currently running...**
- SpongeForge version: 1.10.2-2281-5.2.0-BETA-2464 
- Forge version: 12.18.3.2281        
- Java version: 1.8.0_131
- Operating System:

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

https://gist.github.com/Coolfeather2/c137d86d5c30269d5170e1e4d42133ef

**Comment by Coolfeather2** [comment] 2017-08-08 05:42
Was flying a manticore, dismounted into a creeper and the manticore vanished

**Comment by mezz** [comment] 2017-08-08 06:05
Thanks for the report!
Please report this to Sponge, I'm not sure it's caused by these mods.

**Comment by Coolfeather2** [comment] 2017-08-08 06:13
Okay, done

**Comment by mezz** [comment] 2017-08-08 07:31
Thanks, I'll close this and subscribe to that issue in case it involves Forestry.

**Closed as completed by mezz** 2017-08-08 07:31 UTC
