### ISSUE TITLE
Bees Spreading Mushrooms issue

### ISSUE THREAD

**Issue by TEZMan** [ForestryMC/ForestryMC#688] opened 2015-05-28 17:03 UTC
I had received an analysis from Bdew, and he stated "Something about bees spreading mushrooms is borked." and asked me to report the issue here. 

This is an issue in my 1.7.10 MC server, with the DireWolf20 1.3.1 mod pack.

here is a crash report from my server.
http://pastebin.com/8mws13vP

The issue occurs when certain bee types are placed in a GenDustry Industrial Apiary. I've not tried in other apiaries. Specific bees that I've seen the issue in are Cuprum, Unweary, etc, with the Sieve upgrade installed.

If anyone needs access to do some testing, or more info needed, please let me know.

**Comment by Nirek-K** [comment] 2015-05-28 20:09
Known and already fixed, duplicate of #646
Update to stable 3.5.6

**Closed by Nirek-K** 2015-05-28 20:09 UTC
