### ISSUE TITLE
Reika.DragonAPI.ModInteract.Bees.BeeSpecies.addBreeding

### ISSUE THREAD

**Issue by Sasikaa** [ForestryMC/ForestryMC#1003] opened 2015-12-05 08:47 UTC
This crash log the UPDATED new binnies mod:
bdlib-1.9.4.109-mc1.7.10
binnie-mods-2.0-pre14.jar.disabled (DISABLED beause this mod is crashing Alveary crash...)
gendustry-1.6.3.132-mc1.7.10
generators-0.9.19.120-mc1.7.10
forestry_1.7.10-4.2.1.48

This is my loading CRASH log:
http://pastebin.com/2TQMbVhe

**Comment by mezz** [comment] 2015-12-05 08:54
Thanks for the report!
This is a duplicate of https://github.com/ForestryMC/ForestryMC/issues/849
Please search the issues.

**Closed as completed by mezz** 2015-12-05 08:54 UTC
Labels: duplicate, compat
