### ISSUE TITLE
crash on server start up

### ISSUE THREAD

**Issue by Anora** [ForestryMC/ForestryMC#1291] opened 2016-06-04 16:23 UTC
Mc version: 1.9.4
forge version: 12.17.0.1949
forestry version: 5.0.7.133

net.minecraftforge.fml.common.LoaderException: java.lang.NoSuchMethodError: forestry.core.proxy.ProxyRender.getRendererAnalyzer()Lnet/minecraft/client/renderer/tileentity/TileEntitySpecialRenderer;
    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:179)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:590)
    at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:93)
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:320)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:118)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:429)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: forestry.core.proxy.ProxyRender.getRendererAnalyzer()Lnet/minecraft/client/renderer/tileentity/TileEntitySpecialRenderer;
    at forestry.core.blocks.BlockTypeCoreTesr.<clinit>(BlockTypeCoreTesr.java:25)
    at forestry.core.blocks.BlockRegistryCore.<init>(BlockRegistryCore.java:33)
    at forestry.core.PluginCore.registerItemsAndBlocks(PluginCore.java:112)
    at forestry.plugins.PluginManager.runSetup(PluginManager.java:221)
    at forestry.Forestry.preInit(Forestry.java:89)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:566)
    at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:228)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:206)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:587)
    ... 5 more

**Comment by mezz** [comment] 2016-06-04 22:06
Thanks for the report!
This is a duplicate of: https://github.com/ForestryMC/ForestryMC/issues/1248
We couldn't solve that issue and thought it was fixed, so it was closed. I will re-open it and we can discuss there.

**Closed as completed by mezz** 2016-06-04 22:06 UTC
Labels: duplicate
