### ISSUE TITLE
(1.12.1) Peat Engine might be crashing the server

### ISSUE THREAD

**Issue by domination112** [ForestryMC/ForestryMC#2347] opened 2019-01-21 05:58 UTC
The peat engine seems to have crashed the server when it was placed down. This is the crash log: 
---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-core-1.0.10-1.12.2.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.190.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 1/21/19 12:57 AM
Description: Ticking block entity

java.lang.NoSuchMethodError: forestry.core.utils.InventoryUtil.internal_moveOneItemToPipe(Lnet/minecraftforge/items/IItemHandler;Lforestry/core/tiles/AdjacentTileCache;[Lnet/minecraft/util/EnumFacing;)Z
	at forestry.core.utils.InventoryUtil.moveOneItemToPipe(InventoryUtil.java:82)
	at forestry.core.utils.InventoryUtil.moveOneItemToPipe(InventoryUtil.java:77)
	at forestry.energy.tiles.TileEnginePeat.dumpStash(TileEnginePeat.java:239)
	at forestry.energy.tiles.TileEnginePeat.updateServerSide(TileEnginePeat.java:109)
	at forestry.core.tiles.TileForestry.func_73660_a(TileForestry.java:99)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at forestry.core.utils.InventoryUtil.moveOneItemToPipe(InventoryUtil.java:82)
	at forestry.core.utils.InventoryUtil.moveOneItemToPipe(InventoryUtil.java:77)
	at forestry.energy.tiles.TileEnginePeat.dumpStash(TileEnginePeat.java:239)
	at forestry.energy.tiles.TileEnginePeat.updateServerSide(TileEnginePeat.java:109)
	at forestry.core.tiles.TileForestry.func_73660_a(TileForestry.java:99)

-- Block entity being ticked --
Details:
	Name: forestry:peat // forestry.energy.tiles.TileEnginePeat
	Block type: ID #580 (tile.for.engine_peat // forestry.energy.blocks.BlockEngine // forestry:engine_peat)
	Block data value: 4 / 0x4 / 0b0100
	Block location: World: (-915,93,-115), Chunk: (at 13,5,13 in -58,-8; contains blocks -928,0,-128 to -913,255,-113), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
	Actual block type: ID #580 (tile.for.engine_peat // forestry.energy.blocks.BlockEngine // forestry:engine_peat)
	Actual block data value: 4 / 0x4 / 0b0100
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: world
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 626 Drop: 0
	Level seed: 6104867640925509657
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-902,76,-86), Chunk: (at 10,4,10 in -57,-6; contains blocks -912,0,-96 to -897,255,-81), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
	Level time: 868586 game time, 88995 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 47871 (now: false), thunder time: 15205 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_191, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3321126224 bytes (3167 MB) / 4023386112 bytes (3837 MB) up to 4023386112 bytes (3837 MB)
	JVM Flags: 2 total; -Xmx4096M -Xms4096M
	IntCache: cache: 0, tcache: 0, allocated: 14, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2807 30 mods loaded, 30 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version           | Source                                        | Signature                                |
	|:------ |:------------------- |:----------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2            | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                 | 9.42              | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                 | 8.0.99.99         | forge-1.12.2-14.23.5.2807-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge               | 14.23.5.2807      | forge-1.12.2-14.23.5.2807-universal.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | micdoodlecore       |                   | minecraft.jar                                 | None                                     |
	| LCHIJA | abyssalcraft        | 1.9.4.14          | AbyssalCraft-1.12.2-1.9.4.14.jar              | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| LCHIJA | baubles             | 1.5.2             | Baubles-1.12-1.5.2.jar                        | None                                     |
	| LCHIJA | buildcraftlib       | 7.99.21           | buildcraft-all-7.99.21.jar                    | None                                     |
	| LCHIJA | buildcraftcore      | 7.99.21           | buildcraft-all-7.99.21.jar                    | None                                     |
	| LCHIJA | buildcraftbuilders  | 7.99.21           | buildcraft-all-7.99.21.jar                    | None                                     |
	| LCHIJA | buildcrafttransport | 7.99.21           | buildcraft-all-7.99.21.jar                    | None                                     |
	| LCHIJA | buildcraftsilicon   | 7.99.21           | buildcraft-all-7.99.21.jar                    | None                                     |
	| LCHIJA | buildcraftenergy    | 7.99.21           | buildcraft-all-7.99.21.jar                    | None                                     |
	| LCHIJA | ic2                 | 2.8.108-ex112     | industrialcraft-2-2.8.108-ex112.jar           | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | forestry            | 5.8.2.374         | forestry_1.12.2-5.8.2.374.jar                 | None                                     |
	| LCHIJA | buildcraftcompat    | 7.99.21           | buildcraft-all-7.99.21.jar                    | None                                     |
	| LCHIJA | buildcraftfactory   | 7.99.21           | buildcraft-all-7.99.21.jar                    | None                                     |
	| LCHIJA | buildcraftrobotics  | 7.99.21           | buildcraft-all-7.99.21.jar                    | None                                     |
	| LCHIJA | codechickenlib      | 3.2.2.353         | CodeChickenLib-1.12.2-3.2.2.353-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | customspawner       | 3.11.4            | CustomMobSpawner-3.11.4.jar                   | None                                     |
	| LCHIJA | mocreatures         | 12.0.5            | DrZharks MoCreatures Mod-12.0.5.jar           | None                                     |
	| LCHIJA | mantle              | 1.12-1.3.3.39     | Mantle-1.12-1.3.3.39.jar                      | None                                     |
	| LCHIJA | thaumcraft          | 6.1.BETA26        | Thaumcraft-1.12.2-6.1.BETA26.jar              | None                                     |
	| LCHIJA | twilightforest      | 3.8.689           | twilightforest-1.12.2-3.8.689-universal.jar   | None                                     |
	| LCHIJA | tconstruct          | 1.12.2-2.12.0.115 | TConstruct-1.12.2-2.12.0.115.jar              | None                                     |
	| LCHIJA | galacticraftcore    | 4.0.2.190         | GalacticraftCore-1.12.2-4.0.2.190.jar         | None                                     |
	| LCHIJA | galacticraftplanets | 4.0.2.190         | Galacticraft-Planets-1.12.2-4.0.2.190.jar     | None                                     |
	| LCHIJA | lucky               | 7.5.0             | LuckyBlock_1-12_v7-5-0.zip                    | None                                     |
	| LCHIJA | harvestcraft        | 1.12.2zb          | Pam's+HarvestCraft+1.12.2zb.jar               | None                                     |
	| LCHIJA | llibrary            | 1.7.17            | llibrary-1.7.17-1.12.2.jar                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |

	Loaded coremods (and transformers): 
llibrary (llibrary-core-1.0.10-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.190.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Profiler Position: N/A (disabled)
	Player Count: 0 / 20; []
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Nedelosk** [comment] 2019-01-21 16:45
Duplicate of #2340

**Closed as completed by Nedelosk** 2019-01-21 16:45 UTC
Labels: duplicate
