### ISSUE TITLE
Particles glitch

### ISSUE THREAD

**Issue by ghost** [ForestryMC/ForestryMC#2346] opened 2019-01-20 16:10 UTC
When falling or running in some blocks, their particles are not displayed.
https://i.imgur.com/7RQBODA.png[/img]

**Comment by Nedelosk** [comment] 2019-01-20 16:14
Duplicate of #1200

**Closed as completed by Nedelosk** 2019-01-20 16:14 UTC
Labels: duplicate

**Comment by ghost** [comment] 2019-01-20 16:25
When will it be fixed?
