### ISSUE TITLE
Crash on Minecraft startup forestry_1.10.2-5.2.8.228.jar

### ISSUE THREAD

**Issue by October45** [ForestryMC/ForestryMC#1385] opened 2016-08-12 18:22 UTC
Crash report: http://pastebin.com/Lg1aemqs

**Comment by Moustik2002** [comment] 2016-08-12 18:32
Hi, Same here : http://pastebin.com/Ep0XYWru

**Comment by MakerTim** [comment] 2016-08-12 18:56
Dube of #1384

**Comment by Nedelosk** [comment] 2016-08-12 19:39
Thanks for the report!
But this is a duplicate of #1382.

**Closed as completed by Nedelosk** 2016-08-12 19:39 UTC
Labels: duplicate
