### ISSUE TITLE
Forge fluidstack crash (unstable build)

### ISSUE THREAD

**Issue by Tsunayoshi** [ForestryMC/ForestryMC#609] opened 2015-04-12 10:54 UTC
This happend on opening any block with a fluid inside
http://pastebin.com/Nc8VuNqt

forge-1.7.10-10.13.3.1370-1.7.10
forestry_1.7.10-3.6.0.527-unstable

**Comment by Chocohead** [comment] 2015-04-12 11:02
Already been fixed in 528: https://github.com/ForestryMC/ForestryMC/commit/b8b7ea328f2212938a369f693930912306ae392b

**Closed** 2015-04-12 11:15 UTC

**Comment by Tsunayoshi** [comment] 2015-04-12 11:31
Wohoo nice work!!!

**Comment by mezz** [comment] 2015-04-12 21:57
Dupe of https://github.com/ForestryMC/ForestryMC/issues/604
