### ISSUE TITLE
Engines not connecting to BuildCraft kinetic pipes

### ISSUE THREAD

**Issue by tobast** [ForestryMC/ForestryMC#1898] opened 2017-11-24 12:01 UTC
[Build: 213]

This issue might be connex with #1893. When placing an engine (clockwork, peat-fired, biogas, electrical), the engine does not connect to BuildCraft's wooden kinetic pipes at all, while BuildCraft's native engines do.

Unless I missed some update on how those are supposed to work, I guess they're supposed to connect to wooden kinetic pipes.

This issue was observed with BuildCraft's build 7.99.12. Although this build is recent and alpha, it seems to me that the bug lies on Forestry's side, but I might be wrong with that.

Thanks!

**Comment by Nedelosk** [comment] 2017-11-24 12:10
Duplicate of #1691

**Closed as completed by Nedelosk** 2017-11-24 12:10 UTC
Labels: duplicate
