### ISSUE TITLE
1.9.4-5.0.12.149 crashes dedicated Forge 1.9.4 build 1960 on startup

### ISSUE THREAD

**Issue by kreezxil** [ForestryMC/ForestryMC#1317] opened 2016-06-12 22:45 UTC
Is this still related to Farseek?

Issue:  forestry-1.9.4-5.0.12.149 crashes dedicated Forge 1.9.4 build 1960 on startup

crash report:
https://gist.github.com/2f73c23bd5be99b476192b0b0d88bff5

fml server latest:
https://gist.github.com/8fb3ac6e59d6697b61f670899c9ded11

**Comment by mezz** [comment] 2016-06-12 23:21
Yes, this is the same crash.
Duplicate of https://github.com/ForestryMC/ForestryMC/issues/1248

**Comment by mezz** [comment] 2016-06-12 23:22
https://github.com/delvr/Farseek/issues/10

**Closed as completed by mezz** 2016-06-12 23:21 UTC
Labels: duplicate
