### ISSUE TITLE
Habitat Former giving permanent particle effects to players.

### ISSUE THREAD

**Issue by zach2045** [ForestryMC/ForestryMC#2417] opened 2019-05-28 05:03 UTC
Forestry Version: 5.8.2.387

After placing the Habitat Former on our server I started to notice that I had small blue and orange particle affects around my character. No matter what I try and do I am unable to remove them. I have moved far away from the machine, broken it, died in game, gone to a different dimension, restarted the server a few times and even change the config to have no particle effects and still they remain. Is there any way to remove them?

**Comment by pyure** [comment] 2019-06-01 06:36
Dupe of #2375

(Also: Can confirm this issue)

**Closed as completed** 2019-09-26 19:48 UTC
Labels: duplicate
