### ISSUE TITLE
Crash when rendering bee in inventory (5.0.5-130, forge 1.9.4 - 12.17.0.1948)

### ISSUE THREAD

**Issue by ColinGBos** [ForestryMC/ForestryMC#1283] opened 2016-06-04 03:56 UTC
When I open a chest containing a bee, the game crashes with this log
http://paste.ee/p/7y8Lk
The log says something about a config option for invalid alleles?

**Comment by mezz** [comment] 2016-06-04 06:58
Dupe of https://github.com/ForestryMC/ForestryMC/issues/1276

> One of the first Forestry 5 release broke all the genes.
> In your config/forestry/common.cfg set genetics.clear.invalid.chromosomes to true.

**Closed as completed by mezz** 2016-06-04 06:58 UTC
Labels: duplicate
