### ISSUE TITLE
Crash: Sipiri trees / Greenheart leaves

### ISSUE THREAD

**Issue by emkeev** [ForestryMC/ForestryMC#1842] opened 2017-09-05 21:13 UTC
Problem: Server suddenly crashed. Seems to cite the generation of Greenheart leaves. 

Logs (3, first is original crash and the other 2 are from restart attempts): 

https://gist.github.com/emkeev/10d21d24637883356fce557a3ac392e2

Background info: I have 6 multifarms. 3 of them are wood farms. I have bred all forestry trees and I always imprint them with fireproof, height average, saplings high, and a few other things before I put them in the farm. I harvested over 100k logs of cocobolo, mahoe, and zebrawood before I switched over to sipiri, palm, and plum. In general, farms seem to have a LOT of difficulty clearing leaves from overtop of the farm. Farm is located at a negative Z coordinate which server admin believes is related to the issue.

Minecraft version 1.10.2
Forestry version 5.2.17.385
Forge version 2.0.0.38
Playing FTB Beyond

**Comment by mezz** [comment] 2017-09-07 03:19
Thanks for the report!
This has been fixed in later versions. I will backport the fix to 1.10.

Forestry farms do not clear leaves at all, it's left to naturally decay. There are other mods you can use to destroy leaves if you want.

**Comment by mezz** [comment] 2017-09-07 03:20
Duplicate of #1819

**Comment by mezz** [comment] 2017-09-07 03:30
Fixed in the next release.

**Closed as completed by mezz** 2017-09-07 03:30 UTC
