### ISSUE TITLE
bug with interafce

### ISSUE THREAD

**Issue by MrReps** [ForestryMC/ForestryMC#664] opened 2015-05-13 16:06 UTC
hello,
I have a big probleme with your forestry 3.4.0.7 i can't open the sqweezer and other machine please correct this bug and tanks for your jobs ^^

**Comment by mezz** [comment] 2015-05-13 19:06
Thanks for the report!
Please update to the latest version, it has already been fixed.
Dupe of #604

**Closed by mezz** 2015-05-13 19:06 UTC
