### ISSUE TITLE
Multi-Block farm not harvesting Forestry fruit

### ISSUE THREAD

**Issue by CyNightCBG** [ForestryMC/ForestryMC#1996] opened 2018-02-17 19:59 UTC
FTB Revelations 1.4.0-1.12.2
Forestry 1.12.2-5.7.0.238
Binnie Mods 1.12.2-2.5.0.112
Sponge 1.12.2-2586-7.1.0-BETA-2900

Have farm on manual mode, trees will grow. Once the fruit is ripe, the animation will show it being harvested, however, there is no fruit in the output. Tried placing a Hatch to output to external inventory, no fruit shows up upon being harvested. Tested with Pam's Harvestcraft trees/crops and fruit is harvested and shows up in the external inventory, and in the output in the GUI w/o hatch attached. Vanilla crops will also harvest correctly.

**Comment by CyNightCBG** [comment] 2018-02-17 20:01
In addition, you can not right click the fruit off the trees either.

**Comment by Nedelosk** [comment] 2018-02-17 20:20
Duplicate of #239

**Closed as completed by Nedelosk** 2018-02-17 20:20 UTC
Labels: duplicate, Trees
