### ISSUE TITLE
[1.9] (Farseek) Server Crash on Startup (java.lang.NoSuchMethodError)

### ISSUE THREAD

**Issue by aking4125** [ForestryMC/ForestryMC#1248] opened 2016-05-26 00:08 UTC
The earlier fix works for the mod on it's own. But I'm getting a crash once I add all the mods back into the server. So this must have something to do with another mod, though I currently don't know which one. I'll manually re-add each mod one at a time and see what happens. Here's the crash report: 

https://gist.github.com/mezz/e6f077d3f3aae4f79994ca3e59d6b3ab

**Comment by mezz** [comment] 2016-05-26 00:23
Thanks for the report!
Please upload crash reports to http://gist.github.com in the future, it's easier since I don't need to download them.

**Comment by aking4125** [comment] 2016-05-26 00:56
Gotcha. I got it bookmarked. I'll start re-adding each mod one by one slowly and see what happens. May have to wait a day for my report if anything.

**Comment by mezz** [comment] 2016-05-26 02:32
Ah no need to check other mods, this is 100% Forestry.

**Comment by aking4125** [comment] 2016-05-26 02:33
You sure? The mod by itself works though. Server and client side.

**Comment by mezz** [comment] 2016-06-02 10:08
Hmm I'm no longer so sure. I can't reproduce it. Can you find the conflicting mod?
From experience, it will be fastest to add and remove mods in batches of half at a time.

**Comment by aking4125** [comment] 2016-06-02 19:36
I'll do in a few hours but is it still a valid issue? It seems you updated Foresty to 1.9.4.

**Comment by mezz** [comment] 2016-06-02 20:10
It would have been valid if it was just Forestry, but maybe I fixed it in the meantime as things were shifted around? I don't really like leaving a mystery unsolved but you make a good point, I'll just close it.

**Comment by mezz** [comment] 2016-06-04 22:07
This has been reported again on the latest Forestry version.

**Comment by mezz** [comment] 2016-06-04 23:00
@Anora can you paste your full crash log to https://gist.github.com so I can see the mods involved?

**Comment by aking4125** [comment] 2016-06-05 05:26
I'll look into my 1.9 list to see what is up. I'll return once and if I find the conflicting mod.

**Comment by kreezxil** [comment] 2016-06-05 19:31
Looks like this exists in 1.9.4 build 1954 of Forge too.

Issue:  forestry-1.9.4-5.0.8.141 crashes dedicated Forge 1.9.4 build 1954 on startup

https://gist.github.com/1251b0a673c5fc9d045494ae6f63dcf1

https://gist.github.com/470ae74e0332fb9ff2ab522da168fc1e

**Comment by mezz** [comment] 2016-06-05 19:33
We are looking for which mod causes the conflict. Can you help @kreezxil ?

**Comment by kreezxil** [comment] 2016-06-05 19:37
While not related based on error reports, I've been reporting an issue to
Lordmau5 of Fancy Fluid Storage and they feel it is the Farseek API mod
that is causing the issue and had me redirect my report there. The Farseek
developer does something wicked in the model bakery, perhaps they are doing
some equally malignant with other parts of forge. That is only thing I can
think off of the top of my head.

**Comment by kreezxil** [comment] 2016-06-05 19:38
The thread: https://github.com/Lordmau5/FFS/issues/55

**Comment by mezz** [comment] 2016-06-05 19:42
Not sure it's related, thanks though.

**Comment by aubreybailey** [comment] 2016-06-05 21:13
Confirmed farseek and forestry crash all on their own. Unclear which is the
problem because both work fine with all the other mods

**Comment by kreezxil** [comment] 2016-06-05 21:27
I talked with the farseek author and he said he'll have a fix for his mod in a few days which will fix ffs and forestry too 

-----Original Message-----

**Comment by mezz** [comment] 2016-06-05 21:36
Thanks everyone. 
Closing this issue, subscribe to this farseek one: https://github.com/delvr/Farseek/issues/10

**Closed as completed by mezz** 2016-06-05 21:36 UTC
Labels: Not Forestry
