### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by moran-x** [ForestryMC/ForestryMC#2343] opened 2019-01-19 13:19 UTC
Forestry version: 1.12.2-5.8.2.380
BuildCraft version: 7.99.20 to 7.99.21
Forge version: 1.12.2-14.23.5.2768
Link to crash report or log: https://pastebin.com/3SZT76gR
multiplayer: multiplayer
Steps to reproduce: Update buildcraft from 7.99.20 to 7.99.21
Additional information: ---

**Comment by AlexIIL** [comment] 2019-01-19 14:11
(Originally reported here: BuildCraft/BuildCraft#4326)

**Comment by AlexIIL** [comment] 2019-01-19 14:21
Sorry I should have looked before... but I changed buildcraft's API names from upper case `BuildCraftAPI|transport` to `buildcraftapi_transport` which breaks any `@Optional()` annotations on methods. (For example https://github.com/ForestryMC/ForestryMC/blob/mc-1.12/src/main/java/forestry/core/utils/InventoryUtil.java#L89).

**Comment by AlexIIL** [comment] 2019-01-19 14:29
(Sorry about this, I should have looked at #2340 before - as this is technically a duplicate of that one).

**Closed as completed** 2019-01-20 11:27 UTC
