### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by matyklug18** [ForestryMC/ForestryMC#2210] opened 2018-08-02 18:22 UTC
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Forestry (forestry)
so i am reporting it here

https://paste.dimdev.org/riqakiwico.mccrash

**Comment by temp1011** [comment] 2018-08-02 20:43
Does the game load without ironman?

**Comment by matyklug18** [comment] 2018-08-03 10:53
no, it have another error. but not error with forestry.

**Comment by temp1011** [comment] 2018-08-03 11:31
Pretty sure ironman is what causes the error with forestry. Other stuff I can't tell without log

**Comment by Nedelosk** [comment] 2018-08-03 11:44
Duplicate of #2124

**Closed as completed by Nedelosk** 2018-08-03 11:44 UTC
Labels: duplicate
