### ISSUE TITLE
[1.9][Dupe] Server Crash on Startup

### ISSUE THREAD

**Issue by aking4125** [ForestryMC/ForestryMC#1240] opened 2016-05-25 00:05 UTC
Most likely isn't Server ready but wanna drop this anyways just incase. 
[crash-2016-05-24_20.01.38-server.txt](https://github.com/ForestryMC/ForestryMC/files/280742/crash-2016-05-24_20.01.38-server.txt)

Client seems to work fine.

**Comment by aubreybailey** [comment] 2016-05-25 00:15
duplicate of my https://github.com/ForestryMC/ForestryMC/issues/1239
but im glad we're all stupidly excited :)

**Comment by aking4125** [comment] 2016-05-25 00:31
Ahh didn't notice the dupe. Sorry. I was just curious is all. Not rushing anything. ;) 

If possible, delete this.

**Comment by aubreybailey** [comment] 2016-05-25 00:48
not an admin, just another fan who hurried home from work when i saw that one of the builds actually loaded. I filed the exact same bug just minutes before you ;)

**Closed as completed by aubreybailey** 2016-05-25 00:48 UTC
Labels: duplicate
