### ISSUE TITLE
Compatibility with Buildcraft 7

### ISSUE THREAD

**Issue by kremsy** [ForestryMC/ForestryMC#704] opened 2015-06-06 09:28 UTC
https://github.com/BuildCraft/BuildCraft/issues/2749

Would be cool if this could be investigated as I love both mods!

**Comment by mezz** [comment] 2015-06-06 09:31
Grab [Forestry 3.5.7](http://www.curse.com/mc-mods/minecraft/forestry), released alongside Buildcraft 7 today. It should work fine :)

**Comment by mezz** [comment] 2015-06-06 09:32
Dupe of #702

**Closed as completed by mezz** 2015-06-06 09:32 UTC
