### ISSUE TITLE
Crash Error, Fatal Error in 1.7.10 in Forestry v3.5.3.11

### ISSUE THREAD

**Issue by Cooolaid** [ForestryMC/ForestryMC#622] opened 2015-04-15 04:52 UTC
Illegal Argument Exception: Cannot create a fluidstack from a null fluid

This happens when I try to open or handle machines or anything related to Forestry.
Here is the error log.
http://pastebin.com/W14vqJBX
.

**Comment by mezz** [comment] 2015-04-15 06:10
Thanks for the report!
This is a duplicate of https://github.com/ForestryMC/ForestryMC/issues/604
Please use the latest unstable build of Forestry if you are using the latest Forge. Forestry 3.5.3 works with the "recommended" version of Forge.

**Closed by mezz** 2015-04-15 06:10 UTC

**Comment by Cooolaid** [comment] 2015-04-15 07:08
mezz,
Thank you, omw to get the latest "unstable" build of Forestry. 
thank you for helping me & being kind about it :)
