### ISSUE TITLE
Illegal Argument Exception - Cannot create a fluidstack from a null fluid

### ISSUE THREAD

**Issue by Cooolaid** [ForestryMC/ForestryMC#629] opened 2015-04-17 16:52 UTC
I constructed a Coke Oven and when trying to access its GUI, I get an Immediate crash.
Illegal Argument Exception: Cannot create a fluidstack from a null fluid

I am using (forestry_1.7.10-3.6.0.532-unstable)
http://pastebin.com/75tqRG0H

.

**Comment by laz2727** [comment] 2015-04-17 16:55
Forge version mismatch.

2015-04-17 22:52 GMT+06:00 Cooolaid <notifications@github.com>:

**Comment by Cooolaid** [comment] 2015-04-17 17:08
my forge is - v10.13.3.1370

**Comment by Drakray** [comment] 2015-04-17 22:36
same thing when trying to access Squeezer GUI
http://pastebin.com/PndNmPLK

**Comment by mezz** [comment] 2015-04-17 23:03
Thanks for the report!
This is a RailCraft bug actually. This is also a duplicate of #604
Please use the latest unstable build of Forestry if you are using the latest Forge. Forestry 3.5.3 works with the "recommended" version of Forge.
I will probably fix it soon so that the any build will work with any Forge.

**Closed by mezz** 2015-04-17 23:03 UTC
