### ISSUE TITLE
1.12.1 jei recipy crash foresty crates

### ISSUE THREAD

**Issue by tyler489** [ForestryMC/ForestryMC#1809] opened 2017-08-17 02:21 UTC
Thank you for reporting!

For issues:
 * Try the latest version, it may have fixed the issue already.
 * If you crashed, please paste the crash log to [gist](https://gist.github.com/) and link it here.
forestry_1.12-5.5.0.161.jar
Crash when viewing forestry recipys (carpender)
https://pastebin.com/6BMF0X0e

**Comment by tyler489** [comment] 2017-08-17 05:09
Duplicate?

**Comment by mezz** [comment] 2017-08-17 05:11
Sorry I got mixed up with the JEI issue.

**Comment by Nedelosk** [comment] 2017-09-09 18:32
Duplicate of #1598

**Closed as completed by Nedelosk** 2017-09-09 18:32 UTC
Labels: duplicate
