### ISSUE TITLE
Ticking Entity crash

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [ForestryMC/ForestryMC#649] opened 2015-05-04 18:46 UTC
I'm crashing...randomly...no idea why... http://hastebin.com/juvazozafa.1c

**Comment by Nirek-K** [comment] 2015-05-04 20:46
Duplicate of #646, should be fixed by c705486472480846830d7c7952ec9e8c674b35c1

**Closed by Nirek-K** 2015-05-04 20:46 UTC

**Comment by Nirek-K** [comment] 2015-05-04 21:19
S'Ok, as to the issue, as you can see from the linked one, all that really effects is waterproof bee sealant, and pipe autoextraction, should be fine otherwise.
