### ISSUE TITLE
Multifarm sapling issue

### ISSUE THREAD

**Issue by FlyingScotsman1** [ForestryMC/ForestryMC#1620] opened 2017-03-10 01:52 UTC
I have found that multifarm Managed Arboretum is working great except that any saplings harvested from trees do not first cycle back into the farm to replant before spitting them out into a hopper for collecting, currently I am using Forge 1.11.2-13.20.0.2252 and forestry 1.11.2-5.3.2.55.

**Comment by MauveCloud** [comment] 2017-03-10 02:03
Duplicate of #1461, which mezz declared to be intended behavior.

**Closed as completed** 2017-03-10 22:31 UTC
Labels: duplicate
