### ISSUE TITLE
Disabling ore gen config option not working

### ISSUE THREAD

**Issue by skybix** [ForestryMC/ForestryMC#2636] opened 2022-02-02 04:27 UTC
I tried to disable the ore gen in the config. It didn't work. I tried in an instance with just forestry and world stripper still didn't work. 
forestry-1.16.5-6.0.10.jar

**Comment by ramidzkh** [comment] 2022-02-12 03:00
Duplicate of #2626

**Closed as completed by ramidzkh** 2022-02-12 03:00 UTC
