### ISSUE TITLE
Plant Mega Pack compatibility for Bees

### ISSUE THREAD

**Issue by Voidi** [ForestryMC/ForestryMC#551] opened 2015-03-10 23:27 UTC
Is it possible that bees could recognize the flowers from PMP?
I know there is a config option in apiculture.conf but i don't get it working.
Disregarding that, PMP adds to many Flowers and they even would only fit for particular Bee species,
it would be nice if Forestry could provide compability.

**Comment by CovertJaguar** [comment] 2015-03-12 16:47
Duplicate of issue #223

**Closed by CovertJaguar** 2015-03-12 16:47 UTC
