### ISSUE TITLE
Tconstruct and Foresty

### ISSUE THREAD

**Issue by Ravrous** [ForestryMC/ForestryMC#903] opened 2015-10-21 06:12 UTC
After adding Foresty to my mods I get this error on startup

https://gist.github.com/mezz/5ce7f2a722e88ae99b8b

**Comment by mezz** [comment] 2015-10-21 06:45
Thanks for the report!
It looks like you have a mod with an old version of the RF API, and this conflicts with Forestry. You can try narrowing it down by removing some mods, or just try updating your mods.

Duplicate of https://github.com/ForestryMC/ForestryMC/issues/756

**Closed as completed by mezz** 2015-10-21 06:45 UTC
Labels: duplicate
