### ISSUE TITLE
[1.12] Client Crash java.lang.NullPointerException due to checkNotNull in ModelCrate

### ISSUE THREAD

**Issue by Morpheus1101** [ForestryMC/ForestryMC#1808] opened 2017-08-16 09:51 UTC
MC 1.12
Forge: *.2443
Forestry v5.5.0.163

Crash Log @ https://puu.sh/xboea/8994ba6804.png

**Comment by Nedelosk** [comment] 2017-08-16 12:49
Duplicate of #1598

**Closed as completed by Nedelosk** 2017-08-16 12:49 UTC
Labels: duplicate
