### ISSUE TITLE
Biome Deceration

### ISSUE THREAD

**Issue by bookerthegeek** [ForestryMC/ForestryMC#2116] opened 2018-04-30 08:57 UTC
## Heyo ##
Seems that the mod [Wasteland Reborn](https://minecraft.curseforge.com/projects/wasteland-reborn) and Foresrty has an issue when creating worlds.

[Crash Report](https://gist.github.com/bookerthegeek/056ba00559b031437050beac561b7da9)

**Comment by temp1011** [comment] 2018-04-30 10:36
Confirmed https://gist.github.com/temp1011/3198485b918aca8745373dbb9306b767. Simply create a world with the wasteland type. Setting hives generation amount to 0.0 does fix this. The mod seems to override a lot with worldgen which is probably the cause of the problem.

**Comment by temp1011** [comment] 2018-04-30 10:48
It's passing a `null` position to `DecorateBiomeEvent`. Not sure if forestry should protect against that or if that's a bug in the mod.

**Comment by temp1011** [comment] 2018-04-30 12:34
It seems that this issue has been fixed (https://github.com/Hennamann/Wasteland/issues/7). However, the curseforge page hasn't been updated since February. I would try the newest version from https://maven.henrikstabell.com/com/legacy/wastelands/Wastelands-1.12/1.2.2-11/ which should have the fix in.
EDIT: This crash is fixed in `Wastelands-1.12-1.2.2-11`. I think this can be closed, it's not forestry anyway,

**Closed as completed** 2018-04-30 13:48 UTC
Labels: Not Forestry
