### ISSUE TITLE
Couldn't load loot table forestry:chests/abandoned_mineshaft

### ISSUE THREAD

**Issue by grimuars** [ForestryMC/ForestryMC#1431] opened 2016-09-18 02:16 UTC
Forestry 1.10.2-5.2.11.255
Forge 1.10.2-12.18.1.2089

This message appears when world on dedicated server is loadIng.

`[05:14:55] [Server thread/ERROR] [forestry]: Couldn't load loot table forestry:chests/abandoned_mineshaft from jar:file:/E:/AMS%20Nest%2003/mods/forestry_1.10.2-5.2.12.255.jar!/assets/forestry/loot_tables/chests/abandoned_mineshaft.json
com.google.gson.JsonSyntaxException: Expected name to be an item, was unknown string 'forestry:minerBag'
        at net.minecraft.util.JsonUtils.func_188172_b(SourceFile:134) ~[og.class:?]
        at net.minecraft.util.JsonUtils.func_188180_i(SourceFile:145) ~[og.class:?]
        at net.minecraft.world.storage.loot.LootEntryItem.func_186367_a(LootEntryItem.java:83) ~[bam.class:?]
        at net.minecraft.world.storage.loot.LootEntry$Serializer.deserialize(LootEntry.java:69) ~[bao$a.class:?]
        at net.minecraft.world.storage.loot.LootEntry$Serializer.deserialize(LootEntry.java:45) ~[bao$a.class:?]
        at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58) ~[TreeTypeAdapter.class:?]
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[TypeAdapterRuntimeTypeWrapper.class:?]
        at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[ArrayTypeAdapter.class:?]
        at com.google.gson.Gson.fromJson(Gson.java:803) ~[Gson.class:?]
        at com.google.gson.Gson.fromJson(Gson.java:868) ~[Gson.class:?]
        at com.google.gson.Gson$1.deserialize(Gson.java:126) ~[Gson$1.class:?]
        at net.minecraft.util.JsonUtils.func_188179_a(SourceFile:449) ~[og.class:?]
        at net.minecraft.util.JsonUtils.func_188174_a(SourceFile:457) ~[og.class:?]
        at net.minecraft.world.storage.loot.LootPool$Serializer.deserialize(LootPool.java:144) ~[ban$a.class:?]
        at net.minecraft.world.storage.loot.LootPool$Serializer.deserialize(LootPool.java:138) ~[ban$a.class:?]
        at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58) ~[TreeTypeAdapter.class:?]
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) ~[TypeAdapterRuntimeTypeWrapper.class:?]
        at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72) ~[ArrayTypeAdapter.class:?]
        at com.google.gson.Gson.fromJson(Gson.java:803) ~[Gson.class:?]
        at com.google.gson.Gson.fromJson(Gson.java:868) ~[Gson.class:?]
        at com.google.gson.Gson$1.deserialize(Gson.java:126) ~[Gson$1.class:?]
        at net.minecraft.util.JsonUtils.func_188179_a(SourceFile:449) ~[og.class:?]
        at net.minecraft.util.JsonUtils.func_188177_a(SourceFile:465) ~[og.class:?]
        at net.minecraft.world.storage.loot.LootTable$Serializer.deserialize(LootTable.java:206) ~[bap$a.class:?]
        at net.minecraft.world.storage.loot.LootTable$Serializer.deserialize(LootTable.java:201) ~[bap$a.class:?]
        at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58) ~[TreeTypeAdapter.class:?]
        at com.google.gson.Gson.fromJson(Gson.java:803) ~[Gson.class:?]
        at com.google.gson.Gson.fromJson(Gson.java:768) ~[Gson.class:?]
        at com.google.gson.Gson.fromJson(Gson.java:717) ~[Gson.class:?]
        at com.google.gson.Gson.fromJson(Gson.java:689) ~[Gson.class:?]
        at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:1038) ~[ForgeHooks.class:?]
        at forestry.core.loot.LootTableLoader.loadBuiltinLootTable(LootTableLoader.java:48) [LootTableLoader.class:?]
        at forestry.core.EventHandlerCore.lootLoad(EventHandlerCore.java:106) [EventHandlerCore.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_57_EventHandlerCore_lootLoad_LootTableLoadEvent.invoke(.dynamic) [?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72) [ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168) [EventBus.class:?]
        at net.minecraftforge.event.ForgeEventFactory.loadLootTable(ForgeEventFactory.java:595) [ForgeEventFactory.class:?]
        at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:1048) [ForgeHooks.class:?]
        at net.minecraft.world.storage.loot.LootTableManager$Loader.func_186518_c(LootTableManager.java:148) [bas$a.class:?]
        at net.minecraft.world.storage.loot.LootTableManager$Loader.load(LootTableManager.java:71) [bas$a.class:?]
        at net.minecraft.world.storage.loot.LootTableManager$Loader.load(LootTableManager.java:52) [bas$a.class:?]
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524) [minecraft_server.1.10.2.jar:?]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317) [minecraft_server.1.10.2.jar:?]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280) [minecraft_server.1.10.2.jar:?]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195) [minecraft_server.1.10.2.jar:?]
        at com.google.common.cache.LocalCache.get(LocalCache.java:3934) [minecraft_server.1.10.2.jar:?]
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938) [minecraft_server.1.10.2.jar:?]
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821) [minecraft_server.1.10.2.jar:?]
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827) [minecraft_server.1.10.2.jar:?]
        at net.minecraft.world.storage.loot.LootTableManager.func_186521_a(LootTableManager.java:39) [bas.class:?]
        at net.minecraft.world.storage.loot.LootTableManager.func_186522_a(LootTableManager.java:48) [bas.class:?]
        at net.minecraft.world.storage.loot.LootTableManager.<init>(LootTableManager.java:34) [bas.class:?]
        at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:152) [ls.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:252) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:266) [ld.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_102]`

**Comment by Nedelosk** [comment] 2016-10-18 16:01
Duplicate of #1375

**Closed as completed by Nedelosk** 2016-10-18 16:01 UTC
Labels: duplicate
