### ISSUE TITLE
Dragon Api Bug

### ISSUE THREAD

**Issue by THEVOLCO** [ForestryMC/ForestryMC#890] opened 2015-10-15 14:53 UTC
Hi,

I'm having a Problem with Dragon api. When i Launch my game i get this Crash reporrt:
http://pastebin.com/DmNFX9g

**Comment by bakaxyf** [comment] 2015-10-15 15:29
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/229

**Comment by mezz** [comment] 2015-10-15 16:42
Thanks for the report!
This is a duplicate of https://github.com/ForestryMC/ForestryMC/issues/849

As you can see from the post on Reika Mods Issues, Reika is aware of the problem and being harassed quite a lot. Hopefully there will be a fix soon.

**Closed as completed by mezz** 2015-10-15 16:42 UTC
Labels: duplicate, compat
