### ISSUE TITLE
Forestry 1.11; Cannot render Item - Fatal Crash

### ISSUE THREAD

**Issue by pallen0304** [ForestryMC/ForestryMC#1579] opened 2017-01-28 17:49 UTC
When dealing with Apiarist merchant, bee item for purchase results in fatal crash.

"Description: Rendering item

java.lang.IllegalArgumentException: itemStack must have nbt
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:125)
	at forestry.core.genetics.Genome.getChromosome(Genome.java:139)
	at forestry.core.genetics.Genome.getActiveAllele(Genome.java:178)
	at forestry.apiculture.genetics.BeeGenome.getSpecies(BeeGenome.java:90)"

Crash-Log:
https://gist.github.com/pallen0304/e51adeab736183d1a61351619bf05a5d

Mod acquisition info:
https://minecraft.curseforge.com/projects/forestry?gameCategorySlug=mc-mods&projectID=59751
forestry_1.11.2-5.3.0.30.jar

**Comment by mezz** [comment] 2017-02-02 00:03
Thanks for the report!
Please update Forestry, this has been fixed in the latest version.
According to the log, you have `forestry{5.3.0.4} [Forestry] (Forestry-1.11.2.jar)` and not the jar you expect.
Duplicate of https://github.com/ForestryMC/ForestryMC/issues/1563

**Closed as completed by mezz** 2017-02-02 00:03 UTC
Labels: duplicate
