### ISSUE TITLE
Clockwork engine server crash

### ISSUE THREAD

**Issue by SFort** [ForestryMC/ForestryMC#1555] opened 2016-12-31 13:00 UTC
Another player placed down a clockwork engine and i broke it( in creative). I can not reproduce this but i am still submitting a quick report in case it could happen again.

Server crash: [Pastebin](http://pastebin.com/0jVt9sTa)
Forestry: 5.2.16.347
Forge: 12.18.2.2151
MC: 1.10.2

**Comment by CMCarlsen** [comment] 2017-01-06 11:57
Also having this issue!

MC: 1.10.2
Forge: 12.18.3.2202
Forestry: 5.2.16.348
Crash Report: http://pastebin.com/CMRZdrkq

Issue also occurred when a player on my server was fiddling with a Clockwork engine I believe.

**Comment by mezz** [comment] 2017-01-07 08:29
Thanks for the report!
Unfortunately I was not able to reproduce this bug. 

The engine is getting the block at its position, and the world is returning Air instead of the engine block.
This should not be possible. I suspect another mod may be doing something strange, but I don't have a good way of finding out.

**Comment by SFort** [comment] 2017-01-07 18:56
I believe it only happens if the server is experiencing severe lag. And the player breaks the block while the game thinks the player is not nearby enough to have broke that block.

**Comment by mezz** [comment] 2017-01-10 15:42
I pushed a fix today that may be related to this issue.
Please try with Forestry 5.2.17

**Comment by Nedelosk** [comment] 2017-03-05 14:10
Is this issue fixed ?

**Closed as completed** 2017-04-05 12:42 UTC
