### ISSUE TITLE
Apiarist Villager has broken trade

### ISSUE THREAD

**Issue by PsychotycGoat** [ForestryMC/ForestryMC#1227] opened 2016-05-23 18:47 UTC
Apiarist Villager asks for Oak Wood with a broken damage modifier (32767), which is impossible to get, therefore breaking the trade sequence. Using latest version as of May 23rd.

**Comment by mezz** [comment] 2016-05-23 20:34
Thanks for the report!
Is this for Minecraft 1.7.10 or 1.8.9?

**Comment by PsychotycGoat** [comment] 2016-05-23 20:36
1.7.10, my bad.

**Comment by mezz** [comment] 2016-05-23 20:38
Ah ok. Sorry, but I wasn't able to get to this in 1.7.10. The trade system in 1.8.9 is much better and I've fixed it there.
This is a duplicate of the issue here: https://github.com/ForestryMC/ForestryMC/issues/846
Thanks again for reporting!

**Closed as completed by mezz** 2016-05-23 20:38 UTC
Labels: duplicate

**Comment by PsychotycGoat** [comment] 2016-05-23 20:40
for some reason I didn't find #846 ... all good then!
