### ISSUE TITLE
our trees broke overnight, no fruit

### ISSUE THREAD

**Issue by Dekutanoth** [ForestryMC/ForestryMC#2136] opened 2018-05-22 04:39 UTC
The girlfriend and I run our own private server. She's been breeding trees for a while, While we were playing one night, she tells me her trees are no longer bearing fruit. The "ripe" and "unripe" states are identical in looks, and breaking a "ripe" block of leaves through any means produces no fruit. I used a lumber axe on a large tree with all ripe leaves and got zero fruit. Oddly enough, chestnuts seem to be the only tree that works and gives fruit. 

Here are pictures of the bugged leaves (imgur pasted them out of order, but you get the idea): https://imgur.com/a/67mvmrR

we were on forestry_1.12.2-5.8.0.290 when the trees broke, we updated to forestry_1.12.2-5.8.0.291 but that did not fix the issue.

**Comment by Nedelosk** [comment] 2018-08-13 15:20
Duplicate of https://github.com/ForestryMC/Binnie/issues/404

**Closed as completed by Nedelosk** 2018-08-13 15:20 UTC
Labels: duplicate
