### ISSUE TITLE
[1.12.2] Stairs lighting bug with Optifine

### ISSUE THREAD

**Issue by KorDum** [ForestryMC/ForestryMC#1995] opened 2018-02-17 13:34 UTC
![image](https://user-images.githubusercontent.com/1331559/36341478-fc560e10-13ff-11e8-948a-d91ff766c832.png)

Is it possible to repair it or is it an Optifine problem?
- Forge: 14.23.2.2611
- Forestry: 5.8.0.246
- Optifine: HD_U_C8

**Comment by Nedelosk** [comment] 2018-03-03 20:55
Possibly related to #1817

**Comment by temp1011** [comment] 2018-06-17 15:16
Have you tried changing `disableStairSlabCulling` in the forge config?

**Comment by KorDum** [comment] 2018-06-18 11:11
@temp1011 Yes, I did. It doesn't resolve the problem.

**Comment by Nedelosk** [comment] 2019-09-26 19:05
Duplicate of #1817

**Closed as completed** 2019-09-26 19:05 UTC
Labels: duplicate, Bug-minor, Trees
