### ISSUE TITLE
Forestry Arboriculture Crash: Null Pointer Exception

### ISSUE THREAD

**Issue by Orcinuss** [ForestryMC/ForestryMC#1524] opened 2016-12-08 01:19 UTC
Players who are working with Forestry trees seem to be crashing the server. Server occasionally crashes even when those chunks are not loaded.

**Crash Report**
http://pastebin.com/K1aqL8aY

**Versions**
Forestry: 5.2.16.331
Forge: 12.18.2.171
Direwolf20 FTB Pack v1.1.3

**Comment by Nedelosk** [comment] 2016-12-22 03:32
Have you edited the nbt tags ? If not you have done anything wrong, because you are the only one with this problems.

**Comment by Nedelosk** [comment] 2017-01-01 03:20
Has anyone else this bug, if not I will close this.

**Comment by 6TELOIV** [comment] 2017-01-01 04:49
I'm having this bug on the direwolf20 pack on a server, and it's crashing the server. Very similar errorlog.

**Comment by 6TELOIV** [comment] 2017-01-01 04:49
java.lang.NullPointerException: Exception ticking world
	at forestry.core.genetics.Genome.getActiveAllele(Genome.java:223)
	at forestry.arboriculture.genetics.TreeGenome.getMaturationTime(TreeGenome.java:95)
	at forestry.arboriculture.genetics.Tree.getRequiredMaturity(Tree.java:178)
	at forestry.arboriculture.tiles.TileSapling.getRequiredMaturity(TileSapling.java:59)
	at forestry.arboriculture.tiles.TileSapling.tryGrow(TileSapling.java:92)
	at forestry.arboriculture.tiles.TileSapling.onBlockTick(TileSapling.java:53)
	at forestry.arboriculture.blocks.BlockTreeContainer.func_180650_b(BlockTreeContainer.java:44)
	at net.minecraft.block.Block.func_180645_a(Block.java:480)
	at org.spongepowered.common.event.tracking.TrackingUtil.randomTickBlock(TrackingUtil.java:266)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:653)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:220)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

**Comment by mezz** [comment] 2017-01-01 07:32
`org.spongepowered` Everyone with this issue seems to be running Sponge.
I wonder if they have a better idea of what the problem is. Can you report to them and link back here?

**Comment by Nedelosk** [comment] 2017-03-06 21:40
I have opened an issue: https://github.com/SpongePowered/SpongeForge/issues/1332

**Closed as completed** 2018-05-11 10:29 UTC
