### ISSUE TITLE
[Compatibility Request] add rubber tree breeding

### ISSUE THREAD

**Issue by assassinzghost** [ForestryMC/ForestryMC#2514] opened 2020-01-19 20:44 UTC
Would it be possible to add a tree breeding recipe for IC2/ Tech Reborn rubber trees? 
The functionality only needs to make the leaves/sapling obtainable.

**Comment by Nedelosk** [comment] 2020-02-22 08:58
There currently is no plan to add custom breeding into forestry. Maybe we will think about that if the port of 1.15 is more finished.

**Comment by Nedelosk** [comment] 2020-03-03 20:10
Duplicate of #1482

**Closed as completed by Nedelosk** 2020-03-03 20:10 UTC
Labels: duplicate, enhancement, version: 1.16.x
