### ISSUE TITLE
A BUG

### ISSUE THREAD

**Issue by Andrey228322** [ForestryMC/ForestryMC#1096] opened 2016-03-08 08:50 UTC
[10:35:49] [Client thread/WARN] [FML]: ****************************************
[10:35:49] [Client thread/WARN] [FML]: \* A broken ore dictionary registration with name cropPapaya has occurred. It adds an item (type: class forestry.core.items.ItemFruit) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Forestry for Minecraft report it to them!
[10:35:49] [Client thread/WARN] [FML]: \*  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
[10:35:49] [Client thread/WARN] [FML]: \*  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
[10:35:49] [Client thread/WARN] [FML]: \*  at forestry.core.items.ItemFruit.registerOreDictionary(ItemFruit.java:73)
[10:35:49] [Client thread/WARN] [FML]: \*  at forestry.core.items.ItemFruit.<init>(ItemFruit.java:68)
[10:35:49] [Client thread/WARN] [FML]: \*  at forestry.plugins.PluginCore.registerItems(PluginCore.java:286)
[10:35:49] [Client thread/WARN] [FML]: \*  at forestry.plugins.PluginManager.runPreInit(PluginManager.java:265)...
[10:35:49] [Client thread/WARN] [FML]: ****************************************

**Comment by Parker8283** [comment] 2016-03-08 11:38
What version of Forestry are you running? Could you please provide the full log on [pastebin](http://pastebin.com) or [Gist](https://gist.github.com)?

**Comment by Andrey228322** [comment] 2016-03-08 13:35
forestry_1.7.10-3.6.9.28

**Comment by Andrey228322** [comment] 2016-03-08 13:35
This is message in launcher!

**Comment by mezz** [comment] 2016-03-09 01:01
The latest 3.x version is Forestry 3.6.12, it fixes this issue.
http://minecraft.curseforge.com/projects/forestry/files

Duplicate of https://github.com/ForestryMC/ForestryMC/issues/973

**Closed as completed by mezz** 2016-03-09 01:01 UTC
Labels: duplicate

**Comment by Andrey228322** [comment] 2016-03-20 10:58
Have a problems
http://pastebin.com/C2R1ndhV

**Comment by Andrey228322** [comment] 2016-03-20 11:44
forestry_1.7.10-3.6.12.3

**Comment by mezz** [comment] 2016-03-20 20:51
`[FML]: There is a binary discrepency between the expected input class bdp (bdp) and the actual class. Checksum on disk is 5ec4c010, in patch c32ee1d1. Things are probably about to go very wrong. Did you put something into the jar file?`

Do not edit the minecraft.jar file! Mods go in the `mods` folder. You should not unzip or edit any jars.

Also please make a new issue for different reports, this is not related to your first report.
