### ISSUE TITLE
IC2 Crop support has a potential bug

### ISSUE THREAD

**Issue by Speiger** [ForestryMC/ForestryMC#1030] opened 2015-12-31 14:53 UTC
https://github.com/ForestryMC/ForestryMC/blob/dev/src/main/java/forestry/plugins/compat/PluginIC2.java#L362

Well @sfPlayer1 if you look at the crop CropVenomilia class into the max size function then you will see that it is 6 and the optimal harvest size is 5. So if we skip growth 5 (or the delay is smaller then the farm has time to check it) then it will be never harvested.
I suggest use the function canBeHarvested instead of checking the size...

**Comment by mezz** [comment] 2015-12-31 15:25
@estebes can you respond to this?

**Comment by estebes** [comment] 2016-01-03 10:28
This is not really a bug but more of a property of ic2 crops. The thing with canBeHarvested is that some crops can be haversted before being on their optimal size. For example if you use canBeHarvested and you have stickreeds you will never haverst resin because the crop can be harvested at stage 3 but it will only produce resin at stage 4. To "fix" this particular case change crop.getSize() == crop.getCrop().getOptimalHavestSize(crop) to crop.getSize() >= crop.getCrop().getOptimalHavestSize(crop). You also need to change ItemStack[] cropDrops = crop.harvest_automated(true); to ItemStack[] cropDrops = crop.harvest_automated(false); because this harvesting function also makes use of getOptimalHarvestSize. 
Hopefully when i create the full farm logic for ic2 crops these minor things will all be taken into consideration.

**Comment by Speiger** [comment] 2016-01-03 11:22
Farms are not there to harvest the Crops optimal @estebes. Else they would be way to OP. Thats why i think it should only harvest them when they are harvestable, if you want the best harvest you have to do it manually... Or use a Detector Block or something to detect the steps...

**Comment by estebes** [comment] 2016-01-03 11:28
My logic is to mimic the crop harvester with a cropnalyzer  and some crop-matron benefits so no its not op. Its basically the same as ic2 machines except it has the drawbacks of forestry multifarms (fertilizer, water)

**Comment by Speiger** [comment] 2016-01-03 13:50
Oh well... Multifarms do not have so much logic... Or does it require a Cropanalyzer to craft them?
Thats why they can not check that.. If you change the recipe when IC2 is loaded then everything is fine...

**Comment by estebes** [comment] 2016-01-03 15:01
I dont think you understand the code i use in the multifarm logic. I use the function that is used in ic2 to calculate crop drops. Both multifarms and the ic2 crop harvester have exactly the same output.

**Comment by Speiger** [comment] 2016-01-03 15:17
I do not care how you handle the crop drops gaining, i care about how you handle the crop harvest logic... (If a crop tells  to early that it is harvestable then it is the problem of the user to find a way to make it better..., thats what all mods making wrong. They make it to easy...)

**Comment by estebes** [comment] 2016-01-03 15:20
That is exactly how the ic2 crop harvester works. If you put a cropnalyzer inside the ic2 crop harvester it will only harvest crops when crop.getSize == optimalSize. So im just transferring logic i am not buffing anything. I'm not going to nerf something that shouldn't be nerfed. When i first created this pr it was to give players more options not to give them a useless thing just because.

**Comment by Speiger** [comment] 2016-01-03 15:23
Jup but for forestry farms it should be canBeHarvested instead of Optimal size... (also you should check canBeHarvested anyways...)

**Comment by estebes** [comment] 2016-01-03 15:29
No it shouldn't and i'm not changing it. Your way of doing thing is super broken and does not work. Some crops would be useless because you would never get what they drop because they would always be harvested before getting to the stage where they should be haversted (stickreeds and coffee being the main crops affected by the change).

**Comment by Speiger** [comment] 2016-01-03 15:39
Yeah and that is reasonable simply because these crops should be manual...

**Comment by estebes** [comment] 2016-01-03 15:40
so what you are saying is that ic2 itself is broken and not my forestry implementation.................. this is an ic2 experimental compatibility patch and not an
 ic2 classic one. As simple as that. Hack it if you dont like it.

**Comment by Speiger** [comment] 2016-01-03 15:48
If IC2 Exp adds something then it is their thing. But if you add something that also support IC2 Classic then it should be for both balanced.... (Make a Exp Only thing and then i do not care anymore)

**Comment by estebes** [comment] 2016-01-03 19:20
its ic2 exp only then

**Comment by Speiger** [comment] 2016-01-03 19:34
Good luck because Forestry can not detect IC2 Exp stuff only because IC2 Exp has not its own ModID xDDD
Edit: At least with @Optional

**Comment by estebes** [comment] 2016-01-03 19:44
That is something you have to deal with not me.

**Comment by mezz** [comment] 2016-01-03 20:42
Alright so this is working as intended. From what I understand the original issue is an IC2 bug, and estebes's method is the safe way to ensure that the automation is worthwhile.

**Closed as completed by mezz** 2016-01-03 20:42 UTC

**Comment by estebes** [comment] 2016-01-04 02:56
not an ic2 bug just how crops work
