### ISSUE TITLE
Very easy dupe with backpacks 1.10.2 build 347

### ISSUE THREAD

**Issue by LunyashaRu** [ForestryMC/ForestryMC#1557] opened 2017-01-02 15:30 UTC
1. Find two backpacks of the same type
2. Put at least 2 items into each of backpacks
3. Fill empty slots with items
4. Change backpack mode to Resupply
5. PROFIT

Video Example https://www.youtube.com/watch?v=4a1Eaoizge8

**Comment by mezz** [comment] 2017-01-02 20:31
Thanks for the report! Duplicate of #1530

**Closed as completed by mezz** 2017-01-02 20:31 UTC
Labels: duplicate
